python/devguide

docquality.rst, faq.rst
Closes #16.
This PR:
- removes references to the devguide's source being hosted at ``hg.python.org``.
- changes references to the devguide in examples within the ``faq.rst``
- changes ``hg.python.org/devguide`` to ``hg.python.org/cpython``
- changes the convenience alias ``dg`` to ``c3``
=> Remove references to devguide source on hg.python.org

buildbots.rst
Can be added back in once the move to GitHub is over and we know how it will
act in that instance.
=> Drop mention of using Mercurial username for filtering.

gitdevs.rst
=> Update gitdevs.rst to point out that only ancillary repos still use hg

gitdevs.rst
There was a little bit of ambiguity in the language about what we are talking about _commit_ or _history graph_ and the changeset number mentioned in the text supporting it was not matching the changeset number in the history graph.
=> Removed ambiguity under topic Mercurial for git developers

coredev.rst
We don't clearly document anywhere the additional expectations
that apply to core developers merging changes that don't apply
to folks contributing in other ways.
This new section is an initial step in addressing that omission.
=> Clarify core developer responsibilities

committing.rst
Update the example when committing to git to use bpo-NNNN prefix.
e.g.
```
git commit -m 'bpo-12345: fix some issue.'
```
=> committing.rst: Update git commit message example

setup.rst
https://cpython-devguide.readthedocs.io/setup.html#getting-the-source-code says that core-devs use a different URL to clone, and links to https://cpython-devguide.readthedocs.io/coredev.html#coredev , but the latter doesn't include any URL.
Since the note seems obsolete (the URL is the same for core-devs too), I removed it.
=> Remove outdated mention of a different URL for core-devs.

README.rst
Replace
http://cpython-devguide.readthedocs.io/en/latest/ (returns 404)
with
https://cpython-devguide.readthedocs.io/
:)
=> README.rst: fix devguide URL

communication.rst
I have made few changes to section 12.1 as I felt appropriate, reference - "Add tips for effective online communication to devguide #9"
=> Update to section 12.1

index.rst
I updated the quick start, trying to making it more compact and clarifying a few points (e.g. users should clone the repo from their own account, not from python/cpython).
=> Update the quick start.

triaging.rst
This removes the retired devguide component as noticed in #97.
(I tried editing this directly from GitHub but since it doesn't show me a preview I created a PR to see the diff.)
=> #97: remove retired "devguide" component from triaging.rst

coredev.rst
This removes the link to Python core team from the devguide since the team is not visible to public.
=> Fixes Issue #124: Removes link to Python core team on github

pullrequest.rst
The sentence in `Crediting` section (https://docs.python.org/devguide/pullrequest.html#crediting) reads:
`You may be asked to make these edits on the behalf of the core developer you accepts your pull request.`
I think it should be 
`You may be asked to make these edits on the behalf of the core developer *who* accepts your pull request.`
=> Fixes grammar in pullrequest.rst crediting section

pullrequest.rst
Now that Python has transitioned from Mercurial patches to Git pull requests, the page "Lifecycle of a Pull Request" should exclusively discuss pull requests and not patches.
=> Remove references to patches in pullrequest.rst

compiler.rst
In `compiler.rst` a reference to `spark.py`, used until Python `3.4`, is still present. [issue19655](https://bugs.python.org/issue19655) changed that for `Python >= 3.5` so, this PR simply removes the references to `spark.py` and changes the text under `asdl.py`.
=> remove references to spark.py

gitbootcamp.rst, index.rst
The no frills guide to git.
Closes https://github.com/python/devguide/issues/125, https://github.com/python/core-workflow/issues/27
=> Add Git Bootcamp page

committing.rst
- reference the Git bootcamp page
- forbid committing straight to the main branches (master, 2.7, 3.5, 3.6)
- recommend cherry_picker.py
- explain backport/cherry-pick labels
Closes https://github.com/python/devguide/issues/126
=> Improvements to Committing.rst

index.rst, pullrequest.rst
This addresses #142.
Really just added the instruction of the bot to the licencing section. Tweaked some of the wording too
I also added a note to the quick-start to make sure people actually see it. If the note seems too intrusive I can just place it at the end of the 7th list item as suggested.
=> Add ni instructions to licencing, make it more visible in quickstart

gitbootcamp.rst
- set up an SSH remote for the contributor's CPython fork
- check out a local branch based on their PR branch
- make changes and push them back to their fork
=> Issue #129: Guide to editing PR branches

pullrequest.rst
Closes https://github.com/python/devguide/issues/159
=> Explain why commits in a PR shouldn't be squashed.

committing.rst, pullrequest.rst
"The pullrequest page should include a step-by-step list with the required git commands required to create a pull request."
Closes https://github.com/python/devguide/issues/103
=> adding pullrequest guide for #103

committing.rst
Commits will be squashed right before the PR gets merged
via GitHub UI.
It is preferred that commits in a PR are not squashed so tha
we can view the diff from one commit to another.
Closes https://github.com/python/devguide/issues/164
=> Remove mention of squash commits

pullrequest.rst
As @Mariatta note, there is the instruction of how to download (checkout) other's pull request, but there isn't reference in `pullrequest.rst`.
This patch add a reference to it.
=> Add reference to downloading others patches

pullrequest.rst
Closes https://github.com/python/devguide/issues/161
=> Document when a review can be dismissed.

committing.rst
Remove the part about merging into master.
Remove the part about prefixing the PR title with `X.Y`, cherry_picker.py already does this.
Closes https://github.com/python/devguide/issues/173
=> Update backport instructions

documenting.rst
Two minor tweaks in wording and a fix of the `attribute` directive example that used `data` instead of `attribute`.
=> Minor tweaks in documenting.rst

committing.rst
lol also just now noticed the typo 😛 
Background: https://mail.python.org/pipermail/core-workflow/2017-May/000991.html
=> We don't need to apply `cherry-pick for *` label anymore.

gitbootcamp.rst
Remove the part where it says 'core dev is expected to backport'.
No reason a contributor shouldn't be able to do the backport themselves.
If the contributor can do the backport and resolve conflicts on their own, then it's less work for core devs.
The only thing core dev needs to do is remove the label from original PR, and then approve and merge the
backport PR. :)
I think perhaps better for core dev to specify whether they want to do the backport themselves (so they can do
local testing) or ask the contributor to do it.
=> Update backport instruction

gitbootcamp.rst
On Windows, the single and double quotes should be reversed
Closes https://github.com/python/devguide/issues/217
=> Update git pr instruction

gitbootcamp.rst
The original instruction is to merge with `origin/master`.
I think it's more accurate to merge with `upstream/master`, where `upstream` has been referenced throughout the document as cpython's repo, and `origin` refers to our own fork.
If our `origin/master` is not up to date, we might not see the right result.
So I think it's better to merge with `upstream/master`.
=> Adjust Editing Contributor's PR section of the bootcamp

pullrequest.rst
It was placed above Pull request Guide Step-by-step section.
Moving it `Licensing` section.
=> PR lifecycle: Fix the target to cla

index.rst
A link to setup.rst was missing its :ref: prefix.
=> Fix link from index.rst to setup.rst

index.rst
For the urls, I used this page https://www.python.org/downloads/ because
for some releases, the download link was wrong
=> Fix the urls for the last releases of each major version.

Makefile, make.bat, tools/serve.py
Borrow from python/cpython documentation, add `make serve` to serve devgudie at localhost (port 8000).
If the doc didn't build up, it will first build up then serve the devguide.
=> Add make serve to makefile

README.rst
Closes https://github.com/python/devguide/issues/231
Changed the canonical URL for the devguide to point to the new
subdomain and removed mention of the old mirror.
=> Update devguide URL

compiler.rst
The old link for this paper is broken (or at least doesn't link to the paper in question). A quick google search revealed a few other places where the paper can be found. I opted for the link on legacy.python.org but any of the other links could be used if they better suit the documentation style.
I've run `make html` and it seems to have worked fine 😄
=> Trivial: Fix broken link for Peephole Optimizer Paper

pullrequest.rst
- first ask the original author to do it
- wait a week before converting a patch by another author
- ensure both parties sign CLA
- provide attribution to the original author
Closes https://github.com/python/devguide/issues/195
=> Explain the requirements for converting bpo patch to GitHub

communication.rst
=> Add additional repositories for the contributors

gitbootcamp.rst
Sorry about the other whitespace changes.  I had to reinstall my editor today and it looks like it must have automatic linting turned on or something.  Until I pushed the commit, I didn't realize it had done that. 
Closes https://github.com/python/devguide/issues/249
=> Add how to make a branch for a release other than master

index.rst
Python 3.5 just entered security fixes only:
https://mail.python.org/pipermail/python-dev/2017-August/148794.html
Update also the most recent binary release: 3.5.3 => 3.5.4
=> Python 3.5 entered security fix only stage

gitbootcamp.rst
Move ``Backporting Merged Changes`` section to right after the ``Accepting and Merging a Pull Request``
Closes https://github.com/python/devguide/issues/238
=> Clarify which commit hash is used for backporting

committing.rst, gitbootcamp.rst, pullrequest.rst, setup.rst
This is part of #120.  The goal of this PR is to reorganize the git commands, that are currently scattered around a few pages.
The steps are:
The end result will be:
* setup.rst with basic setup instructions and links to the commands
* pullrequest.rst with the bulk of commands that are common to both contributors and core devs in a reasonable order
* committing.rst with info specific for core devs
* gitbootcamp.rst with a FAQ-like, ctrl-f-able list of most of the git commands
See also #262.
=> Reorganize git commands

committing.rst, pullrequest.rst, setup.rst
This is part of #120, and it builds on #263. The goal of this PR is to reorganize the setup and pullrequest pages.
The end result will be:
* The setup page will include all the necessary information for the initial setup.  This will need to be done once.
*  The pullrequest page will include all the steps from creating a branch to getting it merged in CPython.
=> Update the setup and PR lifecycle pages

committing.rst, coverage.rst
This fixes 11 of 12 complaints by make check, but there is still one I don't know what to do with:
```
PS devguide> .\make check
[2] .\gitbootcamp.rst:282: default role used
1 problem with severity 2 found.
```
I think this last is a false alarm, but there doesn't seem to be any escaping it short of change to rstlint.py to recognise literal blocks. The offending item is the command nested with backticks in:
```
$ git checkout `git rev-list -n 1 --before="yyyy-mm-dd hh:mm:ss" master`
```
=> Fix whitespace and quoting issues identified by "make check"

docquality.rst, make.bat
Add to the Windows build script a clause to create and use a virtual
environment and install Sphinx there, comparable with the Unix Makefile.
The user may suppress this behaviour by defining a her preferred command
in the environment variable SPHINXBUILD, as before.
=> Build in a virtual environment on Windows (#267)

gitbootcamp.rst, pullrequest.rst
This PR contains the changes as proposed in https://github.com/python/devguide/issues/199.
There are two questions for the backport:
- Should we put the branch? [X.Y]: from the last comment it seems we don't want to but most commits have it at the moment. This PR assumes we don't want to.
- Should we have any reference to the backport PR? This PR assumes the answer is no.
First time contributing to devguide. Happy to change wording/structure/whatever as appropriate 😄 
I've split the change into four commits to follow the structure of the issue but probably makes more sense to squash them together (maybe at merge time?)
Solves #199
=> Improve instructions on commit messages

index.rst, pullrequest.rst
Add a link to the open PR with tag [`awaiting-review`](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Aopen+label%3A%22awaiting+review%22) and another one pointing to [how to review pull requests](https://docs.python.org/devguide/pullrequest.html#how-to-review-a-pull-request).
The objective is to try to promote non-core developers to help out with the reviews as stated in #194
Closes #194
=> Add links to promote reviews by non core-developers

buildbots.rst, committing.rst, communication.rst, compiler.rst, devcycle.rst, developers.rst, docquality.rst, documenting.rst, fixingissues.rst, gdb.rst, gitbootcamp.rst, index.rst, motivations.rst, pullrequest.rst, setup.rst, stdlibchanges.rst, triaging.rst
Primary aim is to conform to the 80 character rule (where possible). At the same time I've cleaned up other formatting faults in the same area as the long lines.
I don't personally like to re-flow paragraphs further than end of the affected sentence when I'm writing, so I mostly haven't. It makes it easier to see what changed.
=> Limit line length to 80 & clean-up nearby formatting.

developers.rst
=> Add entry to developer log.

committing.rst
Makes committing.rst consistent with the rest of the guide in having
just one top-level section. This eliminates a surprise navigation where
18 comes next after 16.
In the file history, this section (as "Working with Mercuruial") grew too large and was promoted in-place (commit e8b299e9), I infer, preparatory to a move that never came. Then it shrank again as sub-sections went to many other places in the guide.
=> Demote "Working with Git" within committing.rst

committing.rst
* It's not a best practice
* It doesn't make news files more readable
* It's easy to confuse its syntax with Markdown
* And it adds unnecessary steps to contributing process.
Contributors shouldn't have to remember which style should be
used in news files and the rest of the documentation.
* Sphinx's default_role setting defaults to None
(http://www.sphinx-doc.org/en/stable/config.html#confval-default_role)
and neither Doc/conf.py nor blurb set it explicitly so the meaning of
default_role can change in future releases of Sphinx.
=> Don't recommend single backticks in news files

tools/templates/layout.html
=> Make the copyright in the footer into plain text.

committing.rst
The filenames for news snippets in subdirectories of `NEWS.d/`, as generated by `blurb`, include both the date and time ([source](https://github.com/python/core-workflow/blob/master/blurb/blurb.py#L186)).  The current description in `committing.rst` only mentions the date.  This PR updates the description to match the behaviour of `blurb`.
=> Make News.d/next filename description match blurb

committing.rst, pullrequest.rst
When converting other people's patch, ensure to add the "Co-authored-by:" message.
=> Mention how to add co-author info.

documenting.rst
Fixes https://github.com/python/devguide/issues/323
=> Documenting: Mention blurb as a doc build dependency.

triaging.rst
The goal of this PR is to provide people new to triaging a cheatsheet-like view of the fields on bugs.python.org.
This is a first step in possibly creating a "triaging workgroup".
=> Update triage page with tables

index.rst
> Let's not play games with semantics. The way I see the situation for 2.7 is
that EOL is January 1st, 2020, and there will be no updates, not even
source-only security patches, after that date. Support (from the core devs,
the PSF, and python.org) stops completely on that date. If you want support
for 2.7 beyond that day you will have to pay a commercial vendor. Of course
it's open source so people are also welcome to fork it. But the core devs
have toiled long enough, and the 2020 EOL date (an extension from the
originally annouced 2015 EOL!) was announced with sufficient lead time and
fanfare that I don't feel bad about stopping to support it at all.
Guido van Rossum, https://mail.python.org/pipermail/python-dev/2018-March/152348.html
>Sounds good to me. I've updated the PEP to say 2.7 …
=> Update Python 2.7 EOL date

docquality.rst, documenting.rst
For issue #334 .
I've made a few changes in this PR to maybe make building the Python docs clearer.  
- Added a section heading on "Helping with Documentation"
- Added parenthetical text to "Helping with the Dev Guide" section so the reader realizes that it's talking about a different set of docs.
- Moved the 'Building the documentation" section of the "Documenting Python" page from the end to right after the introduction.  I think it's more 'findable' this way.
- Add a short introduction to the 'Building the Documentation' section.
I hope these changes don't step on decisions made in the past, but I think they might help a newcomer navigate more easily.
=> Clarify "Helping with Documentation"

tracker.rst
Partially addresses #120.
This PR is prompted by recent discussion on "core mentorship" list. It's a refresh of the section.
- expand introduction to clarify *bugs.python.org* and *bpo* refer to the issue tracker and include devguide issue tracker location
- migrate text to bullets in "check if issue exists section" for easier reader scanning
- remove the reference to Javascript and nosy list as it's confusing for those newer to the contributing. It is covered well in the nosy list reference on the triaging page.
- Add a heading for "understanding issue progress and status"
- Move section on "Disagreement" above the triaging sections and edit tone
- reflow text and fix minor grammar issues
=> Refresh tracker page on where to file issues

docquality.rst
Edit basics for contributing to docs.
- corrections based on grammarly checker
- convert some passive voice to active
- add bulleted context for the reader at top of section
=> edit basics on contributing docs

conf.py, tools/templates/globaltoc.html
Adds a Sections contents to the sidebar to improve overall usability and UX so all pages one click from sidebar.
- adds a global toctree template
- adds global toctree to sidebar display
Related to PR #349. Merge of this PR should allow the table to be placed lower on the index.rst page.
=> Add Sections contents to sidebar

appendix.rst, index.rst
Related to #40, #120, #189 
This PR adds an Appendix that groups the individual document pages into logical subtopics. The goal of this PR is to gather topics together to help:
- consolidation and refactoring of sections that only have one paragraph
- deduplicate redundant content
My hope is that this can be a first pass and that we can iterate on this in future PRs.
=> add appendix with topic pathways

documenting.rst, index.rst
Addresses #189 
This PR adds navigation by type of user to the top of the devguide index page. This partially solves 2 issues: 
- guide folks by roles to relevant docs in a space efficient manner
- the sidebar toctree navigation requires multiple clicks to get to a particular page in the devguide. This small table gives one-click access to frequently used pages.
=> add navigation table by contributor type to landing page

setup.rst
The mac instructions are a little unclear for python versions >= 3.7 and results in openssl not used in build when using homebrew for deps. This adds instructions on what to do.
=> Added additional instructions to Mac build section for building python >= 3.7

setup.rst
In section: [1.1.2. Getting the Source Code][1]
Need to say 'cpython.git' instead of 'devguide.git'
[1]: https://devguide.python.org/setup/#getting-the-source-code
=> fix: fixed typo in the setup dev guide

coredev.rst
I went through the list of things to do and didn't realize these are separate bits.
Add info on what they do (== how you can check), and explicitly mention the orthogonality.
=> coredev.rst: Clarify "Developer role" and "is commiter" bit are separate

index.rst, setup.rst
- Edit titles to be more consistent with each other
- add "see also: box and link to Quick Reference
- [WIP] clean up macOS build/compile section
- [WIP] better organize the Unix build/compile section
=> [WIP] Edit setup section titles and compiling content

experts.rst
* Added 'contextvars', 'dataclasses', 'secrets' and 'zipapp'.
* Removed 'macpath' because it is deprecated and an implementation  'os.path'.
* Moved 'memoryview' because it is not a module.
=> Update the list of modules in experts.rst.

setup.rst
Updated tool names to match the exact terminology used when installing Visual Studio 2017.
=> Update tool names for Visual Studio 2017

LICENSE, buildworker.rst, clang.rst, communication.rst, compiler.rst, coverage.rst, exploring.rst, gdb.rst, help.rst, langchanges.rst, motivations.rst, stdlibchanges.rst, tracker.rst
Hello,
this is my first `devguide` pull request! 😄
--[**Suriyaa Sundararuban**](https://about.suriyaa.tk/) *([My Python profile](https://www.python.org/users/suriyaa/)) ([My Bugs Profile](https://bugs.python.org/user28717))*
=> Use HTTPS protocol instead of HTTP

documenting.rst
Note that the `Docs\Makefile` and `Docs\make.bat` files in the cpython repo already include this; it's just missing from the docs here.
=> Building docs without make: Add python-docs-theme to requirements list

triaging.rst
There was no languishing status in b.p.o
=> Remove "languishing" status from triaging doc.

committing.rst
The CLA can be checked using an API endpoint in bpo,
passing in the GitHub usernames as comma separated values.
There is a separate PR (https://github.com/python/the-knights-who-say-ni/pull/157) to update the message in ni to link to this new section.
Closes https://github.com/python/core-workflow/issues/269
=> Provide explanation for core devs on how to check for CLA

pullrequest.rst
Instead of asking a core dev to update the CLA status, contributors
should check it for themselves by using the check-python-cla website.
=> Update Pullrequest.RST to mention the check-python-cla website.

gitbootcamp.rst
Clarify how to checkout from the remote.
Provide example using `upstream` instead of `origin`.
=> Update the example on how to checkout maintenance branch

coverage.rst
coverage.py moved to GitHub.
Instead of `hg clone`, do `git clone`.
=> Update the instruction on how to clone coverage.py

index.rst, setup.rst
This PR reorganizes the setup.rst page:
1. There is now a section about compiling Python, followed by a separate section about installing dependencies
2. The commands to compile Python are now just after the section about getting the code
3. The header levels have been fixed
4. Some paragraphs have been rephrased
=> Reorganize the setup.rst page.

triaging.rst
Add some descriptive text and a link to a requirement for targets of the Assigned To field.  I.e. assignees must have the Developer role.
=> Add a link and description for Assigned To

buildbots.rst
Change the mention of the old Mercurial repository to the active GitHub repository including a link to it.
See also: https://github.com/python/devguide/issues/423
=> Change Mercurial reference to GitHub

experts.rst
c.f. https://mail.python.org/pipermail/doc-sig/2018-October/thread.html (thread unarchived yet, message of Xiang Zhang saying "I agree to promote Shengjing Zhu as the repo coordinator.".
=> Adding Shengjing Zhu as the coordinator of the zh-cn translation.

experts.rst
Reverts python/devguide#435
Despite Antoine contacting me directly about my current activity, I find it very difficult to believe that he chose to proceed with this.  Please revert while I update Antoine on my current development effort to bring a new feature to multiprocessing.
=> Revert "Update multiprocessing experts"

gitbootcamp.rst
On the git bootcamp page, Markdown syntax was used for the link to [hub](https://github.com/github/hub), instead of rst syntax.
=> Fix link on the git bootcamp page

setup.rst
Since Ubuntu 18.04 (Bionic Beaver) is a LTS release, update from xenial (16.04 LTS) to bionic in the setup steps.
=> Update xenial to bionic in setup.rst

compiler.rst, grammar.rst
Include/token.h is now generated from Grammar/Tokens (see [bpo-30455](https://bugs.python.org/issue30455)).
=> Update information about token types and add more mark up.

setup.rst
Add a link to the documentation from Victor Stinner to build Python on
windows.
Fixes: #433
=> [Documentation] Add a quick guide link to build.

devcycle.rst
Following on from [this merge and the ensuing discussion](https://discuss.python.org/t/remove-needs-backport-to-3-6-label/563/22), I've drafted this new policy for managing permissions that ultimately lead to someone having the ability to hit Merge on any Python Pull Request and other high level access concerns that go along with GitHub organization Ownership and CPython Repository Administrator role.
=> Implement policies for GitHub Organization Owners and CPython Repository Administrators

devcycle.rst
excluding Release Managers for security mode branches was a mistake,
as they occasionally need admin level privileges to temporarily disable
status checks for their branches.
=> update policy for CPython repository administration

setup.rst
=> setup.rst: Fix typo from 'intall' to 'install'

index.rst
Grammar correction in _Other Interpreter Implementations_ section:
Some major example -> Some major examples
=> Fix minor typo

index.rst
Without the `cd` command, the next step (`configure`) will not find the command.
=> DOC: cd after git clone

pullrequest.rst
`--force-with-lease` is generally less harmful than `--force`  and is usually what people want when they use `--force`.
=> Replace  --force with --force-with-lease

devcycle.rst
Two categories were added during review of https://github.com/python/devguide/pull/480. 
Don't specify the number, so it doesn't need to be updated when categories are added or removed.
=> Fix number

gitbootcamp.rst
We should not recommend "rebase" and "push -f" to new users.
These command requires high skill when they cause trouble.
=> stop recommend rebase for new contributors

gitbootcamp.rst
=> Add introductory note for new and experienced git users

experts.rst
Adding myself to the experts index.
Does anyone know if the auto-nosy index on bpo is populated from this document automatically, or is there somewhere else I need to update for that?
=> Add p-ganssle to experts list for times and dates

triaging.rst
Component of issue python/core-workflow#339 and based on the proposal from https://discuss.python.org/t/proposal-create-bug-triage-team-on-github/992/19.
=> python/core-workflow#339: Add "Python triage team" section to "triaging.rst"

pullrequest.rst
The pull request step-by-step guide provides instructions to create a
git branch using upstream/master as the start-point.  This commit adds
a command to the guide which safely makes sure that this start-point
exists in the local repository.  Fixes #509.
=> Add missing git command to pull request guide

triaging.rst
Component of https://github.com/python/devguide/issues/296.
Currently, this is just a draft including a brief summary and a couple of labels. Working on adding most of the other common labels and applying the correct formatting for the table before opening it for review. Only includes labels that are going to be addable by those in the Python triage team (currently only from the CPython repository). Let me know if I missed any.
Labels to add:
~~DO-NOT-MERGE~~
~~expert-asyncio~~
~~invalid~~
~~needs backport to X.Y~~
~~skip issue~~
~~skip news~~
~~OS-X~~
~~sprint~~
~~type-bugfix~~
~~type-documentation~~
~~type-enhancement~~
~~type-performance~~
~~type-security~~
~~type-tests~~
=> Add "GitHub Labels" section to "triaging.rst"

triaging.rst
Based on discussion: https://discuss.python.org/t/criteria-for-promoting-people-to-the-python-triage-team/2105/
Closes https://github.com/python/devguide/issues/308
=> Add procedure for adding people to the Python Triage team

committing.rst, documenting.rst
Based on the feedback from the [ML thread in Python-Dev](https://mail.python.org/archives/list/python-dev@python.org/thread/HTAFGTQIZJQUCU6QCVF3KFD3VFGFOBWV/#HTAFGTQIZJQUCU6QCVF3KFD3VFGFOBWV) and [Discuss topic](https://discuss.python.org/t/should-news-entries-contain-documentation-links/2127) it seems appropriate to update the devguide accordingly. 
I also adjusted the number of spaces in the indentation from the existing example from 2 to 3 in order to meet [reST standards](https://devguide.python.org/documenting/#use-of-whitespace).
=> Expand "What's New and News Entries" to include Sphinx

exploring.rst
Adds another article to the list of external references to explore the source code.
https://realpython.com/cpython-source-code-guide/
Article is based on 3.8.0b3
=> Contribute article to the exploring page

triaging.rst
In this PR I propose add the stale label on devguide.
Also, move OS-X label to above for a correct alphabetic order.
I would like document the ```awaiting *``` labels, but I don't know if in this section (Github label for PR) is the correct. Some opinion about it?
=> Adding Stale label

gitbootcamp.rst
This PR will apply the following changes to gitbootcamp.rst:
- fix capitalization in some section titles;
- use the long form of will consistently;
- use variables `<x>` consistently.
=> Improve gitbootcamp.rst

setup.rst
1. Mention that `make -j` works w/o specifying the number of cores
2. Add gdbm as a package to install from Homebrew
=> Touch up Getting Started

triaging.rst
Based on the conversation in https://github.com/python/devguide/issues/527, I added a note after the "Responsibilities include" list which specifies that triagers should only close PRs that could be considered spam, but they can suggest for other PRs to be closed. For anything potentially valid (including recently active and older PRs), a core developer should make the final decision.
=> Add guidelines for triagers closing PRs

devcycle.rst
As requested by Pablo on infrastructure-staff mailing list, for managing webhook integrations with the buildbot infrastructure.
If I could get @brettcannon to confirm, we'll merge this and add them to the appropriate team.
=> Add @pablogsal to CPython Repository Administrators

coredev.rst
In case someone other than me needs to onboard a new core developer.
=> Create a TODO list for onboarding

pullrequest.rst
"rebase upstream/master" and "push -f" workflow may corrupt pull request.
See https://discuss.python.org/t/info-rebase-origin-maseter-push-f-workflow-corrupts-pull-request-rarely/2558/3.
And see also #496.
=> Prefer merge over rebase

pullrequest.rst
See the [original discussion on discuss.python.org](https://discuss.python.org/t/info-rebase-origin-maseter-push-f-workflow-corrupts-pull-request-rarely/2558/4?u=taleinat).
This adds detailed instructions on how to deal with merges in two common cases:
1. Pulling other people's commits to your PR branch.
2. Merging in the base (master) branch to resolve merge conflicts.
I've tried to keep to the general tone of the guide, and specifically the "step-by-step" section, keeping things simple, short and straightforward.
=> improve instructions about merging in the step-by-step guide

index.rst
The phrase "Get Setup" should be spelled like "Git Setup". The
former doesn't make any semantic sense, whereas the latter does.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
=> Fix a typo in the Quick Links section

garbage_collector.rst
Minor copy-editing of garbage_collector.rst. Fix a few typos. Break up a few runaway sentences. Make the example coded match the link_1-link_4 explanation more closely. Use consistent naming of link_1-link_4.
=> Minor editorial pass over garbage_collector.rst

experts.rst
Some modules that are removed but not included in this patch (like `_dummy_thread`) kept for bugs in the back versions (like 3.8).
=> Purge removed modules from expert's list

grammar.rst
Now, with the exposed `ast.unparse` interface it is more important then a standard `Tool/` script and needs to reflect changes in the ast.
=> Add ast.unparse to grammar change checklist

setup.rst
=> Add a note about running make clean before or after re-running configure

triaging.rst
The `news` location redirects to https://www.python.org/blogs/ which is not where this is supposed to point. Google seems to suggest the `dev` link is the correct link target here.
=> Fix security reporting issue link target

coredev.rst
Based on what I needed to do for the last core dev who was onboarded.
=> Update the checklist for onboarding a new core dev

grammar.rst
It looks like these docs (specifically the grammar reference for [expressions](https://docs.python.org/3/reference/expressions.html)) got stale when the walrus was added. It's making documenting PEP 614 very tricky.
Also, this checklist is an amazing resource. I was halfway through debugging segfaults in `importlib` before I found this!
=> Add Python Language Reference docs to Grammar checklist.

documenting.rst
The previous table was hard to edit and displayed very narow in the HTML page as newlines were kept, the new one is easier to edit and wider in HTML. Did this to change the link to the spannish github that moved recently.
=> Rewrite translations table and fix link

pullrequest.rst
Closes: #579 
- Add a note to the quick about not modifying the git history
- Explicitly state not using force-pushing at point "7. Review and address comments on your Pull Request"
@aeros What do you think about it?
=> Add a note about not modifying the git history to the quick guide

compiler.rst, grammar.rst
Alas, I don't have the energy to write a full guide on how to actually work with the PEG parser.
=> Update grammar.rst and compiler.rst to describe the PEG parser

developers.csv
https://devguide.python.org/developers/ shows an unexpected indention for one name which begins with an initial and a period:
It's being parsed as an alphabetic `<ol>` starting at the 18th letter, R.
Escaping the intial's dot fixes it:
=> Escape dot to prevent <ol>

developers.csv
Re-apply commit 0427168c1ae4f69aff299fa215dd2ae7aaa0ff15.
This time the issue was fixed in the script that generates the data,
so it shouldn't reappear.
Co-Authored-By: Hugo van Kemenade <hugovk@users.noreply.github.com>
=> developers.csv: Escape dot to prevent <ol>

documenting.rst
Spanish translation of Python documentation is located at new repository under `python` organization.
=> Update Spanish documentation translation repository link

devcycle.rst
Try to be more consistent about use of major.minor.micro version
numbers and of feature, bugfix, and security releases.  Reflect
current policy and practice for branch transitions as of 3.9.
Other minor cleanups.
=> Clarify branch/release terminology in Development Cycle page.

help.rst
Add note that IRC channel may not have history, and thus may not be easily searchable for newcomers.
(I could not easily find a discussion archive)
=> help: Add link to Discourse instance

langchanges.rst
Guido is no longer the BDFL :(
This is now, in a general sense, defined by the Steering Council.
=> change wording re. who defines what is "Pythonic"

buildbots.rst
Fixes issue #467 
Use the Imperative form for the bullet list on the Continuous Integration page ( in buildbots.rst file )
=> Fix issue467- Use the imperative form for the bullet list

coverage.rst
Also on Mac OS X systems.
Instead of code section followed by alternative solutions introduce multiple code sections by system name. This way one can easily skip to section one is intersted in. This way tutorial on virtual env is written as well.
=> Improve steps to install coverage in Virtualenv on Windows (#336)

coverage.rst
Related issue is #593
The documentation around building the c extension for coverage.py is usually not required, as the c extension is usually installed by default. I've added some clarification of this in the docs.
=> Updated docs for coverage c extension

experts.rst
Considering that Stefan is no longer a core developer, it would make sense not to tag them as nosy for issues under his interest. Alternatively, should they be marked as inactive instead?
=> Update experts index

.github/CONTRIBUTING.md
=> CONTRIBUTING: Link to bugs.python.org and python-dev

conf.py
```console
$ sphinx-build -n -W -q -b html -d _build/doctrees . _build/html
/home/travis/build/python/devguide/conf.py:243: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
app.add_stylesheet('custom.css')
The command "sphinx-build -n -W -q -b html -d _build/doctrees . _build/html" exited with 0.
```
https://travis-ci.com/github/python/devguide/jobs/402257689#L244
```console
$ sphinx-build -n -W -q -b html -d _build/doctrees . _build/html
The command "sphinx-build -n -W -q -b html -d _build/doctrees . _build/html" exited with 0.
```
https://travis-ci.com/github/hugovk/devguide/jobs/402347688#L246
=> Fix RemovedInSphinx40Warning: Replace deprecated add_stylesheet with add_css_file

grammar.rst
Since 3.9, we started to document each each individual node in the [AST](https://docs.python.org/library/3/ast.html) docs. It might be a common catch to forget when a new node is introduced or existing ones are updated / removed, so added a checklist entry.
=> Add an entry for Doc/library/ast.rst

committing.rst
These changes are based on issue #520.
Issue #520 was somewhat open ended, so I generally tried to make the text easier to skim so that core developers could use it as a quick reference. 
I'm still learning reStructuredText, so there are some issues with formatting, some of which have caused problems with line lengths in vertical lists.
I'd be interested to know if this kind of simplification is what you were going for. I'm looking forward to hearing how we can keep improving this resource.
=> Issue #520: Made https://devguide.python.org/committing/ simpler

developers.csv
I've removed myself from the Python teams on Github.
In theory, doing open-source development on Python has been my professional-development activity for the past year, but in practice I've gotten very little done on Python, and it seems like time to look for other projects.  If I have Python-related changes or documentation in the future, I'll just file a PR for someone else to assess and merge.
=> Note removal of privileges for akuchling

communication.rst, runtests.rst
The repo changed name, from "performance" to "pyperformance", a while back.  Looks like the devguide did not get updated.  GitHub is kind enough to rewrite the old URL in requests but we may as well update the actual links.
=> Fix the pyperformance Repo URL.

buildbots.rst
The name of the tags classifying the various builders has changed at some point, but the devguide hasn't been updated, so the current link points to a list of 0 builders.
=> Fix link to custom builders

committing.rst
This comment seems to be an old revised mention about codecov's coverage comments from here: https://github.com/python/devguide/pull/80/files#diff-eb1b0e0746ead0f2c05fe91ab3cf886a06b30c20459147869209616b5d2279cbR20-R21
We've long disabled codecov posting comments on pull requests about coverage, and with https://github.com/python/cpython/pull/25679 working to remove the coverage build, we can get rid of this mention.
=> Remove mention of old coverage comment from checklist

buildworker.rst, communication.rst, documenting.rst, help.rst, index.rst, motivations.rst
=> Fix broken links

index.rst, setup.rst
Remove replace description for python2. (It's no longer needed after EOL)
=> Remove replace description for py27 in setup step

docquality.rst
The former sentence used to say "Changes (...) follows (...) and is (...)", but since the sentence subject is a plural then the verbs should be replaced with (they) "follow" and "are". Does that make sense?
=> minor grammar improvement

setup.rst
Py27 is EOF. So we should remove relative notes.
=> Remove py27 notes in Setup Page.

communication.rst, triaging.rst
- Section 11: Remove Zulip refs
- Section 12.2: Replace Zulip with Discourse
Resolves #669
=> Replace Zulip with Discourse

setup.rst
On Windows, the build instructions prompt the user to run `PCBuild\build.bat`. The correct path is `PCbuild\build.bad` if a user copies the path from the copy block in the docs, it won't find the file correctly.
=> fixed capitalization on PCbuild\build.bat

setup.rst
Current advice regarding installing dependencies is insufficient to build all optional modules:
```
The necessary bits to build these optional modules were not found:                                                            
_bz2                  _curses               _curses_panel
_dbm                  _gdbm                 _hashlib
_lzma                 _sqlite3              _ssl
_tkinter              _uuid                 readline
zlib                                                   
To find the necessary bits, look in setup.py in detect_modules() for the module's name. 
```
Some users may like the convenience of getting a head start on choosing OS packages that get them closer to a complete build.
=> Add advice on building all modules on Debian-like

coredev.rst
This pull request changed "requied" to "required" in the "Gaining Commit Privileges" section in coredev.rst.
=> Fix minor typo in coredev.rst

runtests.rst
Cause of the bug:
- The class seems to be reloaded using a different name at the bottom of `https://github.com/python/cpython/blob/main/Lib/test/test_abc.py`
Fix:
- Modify class name in guide.
=> Fixes #717: Example for Running a single test case fails

grammar.rst
=> Add build.bat counterparts to grammar checklist

setup.rst
=> Add instructions on running autoreconf with pkg-config

parser.rst
Some problem I found while reading:
- two typos
- mention the cut in the text (not just the metagrammar)
- add backticks around references to names from the rules
=> Improvements to "Guide to CPython’s Parser"

parser.rst
#765: Add a paragraph saying that actions must not mutate ast nodes
=> add warning about actions mutating things to the parser doc

.github/workflows/ci.yml, runtests.rst, setup.rst, tools/templates/customsourcelink.html
also covers a handful of external references who have similarly made this change
=> rename default branch to main

c-api.rst, conf.py
See the CPython PR: https://github.com/python/cpython/pull/29956
and mailing list discussion: https://mail.python.org/archives/list/python-dev@python.org/thread/64VOMHNR37N4HVPWAHKHJM4UFYJPVKSV/
=> Add guidelines for changing/removing from the Limited API

docquality.rst
Delete "(as well as 2.x)" from:
> The in-development and most recent 3.x **(as well as 2.x)** maintenance
branches are rebuilt once per day.
The footer of https://docs.python.org/2/ and https://docs.python.org/2.7/ say "Last updated on Jun 19, 2020."
=> Docs for Python 2.x are no longer built daily

triaging.rst
Fixes https://github.com/python/core-workflow/issues/418.
=> Triagers cannot rename PRs

experts.rst
As discussed on python/peps#2270 , looks like [Fredrik "effbot" Lundh](https://mail.python.org/archives/list/python-dev@python.org/thread/36Q5QBILL3QIFIA3KHNGFBNJQKXKN7SD/), who has passed away, is still listed here.
Also, the list still mentions and links to [PEP 291](https://www.python.org/dev/peps/pep-0291/) and [PEP 360](https://www.python.org/dev/peps/pep-0360/), stating they contain special rules for some modules. PEP 291 is thoroughly obsolete, being explicitly limited to Python 2, while PEP 360 has not been updated in many years and with any new additions being explicitly prohibited, it presumably never will be, and all the projects currently listed are maintained in the stdlib and no longer active upstream for at least the past decade or more. This was a source of confusion, so …
=> Remove deceased expert and line linking to now-obsolete PEPs with special rules

gitbootcamp.rst, pullrequest.rst, triaging.rst
Keep _Mercurial Repository_ in _Triaging_, since BPO links to it.
Resolves #796
=> Remove outdated Mercurial sections

triaging.rst
The current information on superseders doesn't make it clear that the superseded issue should be entered simply as a number, and that the resolution should be set to "duplicate".
=> Add more information about superseders

coredev.rst
GitHub uses a padlock to indicate private repos.
Add a padlock emoji 🔒 next to the private https://github.com/python/voters/ name.
If you don't have access, GitHub shows a 404 when clicking, making it appear like a broken link: https://github.com/python/devguide/issues/681#issuecomment-1016952381
=> Add padlock emoji to denote voters repo is private

.github/workflows/ci.yml
There were two problems:
1. `actions/cache` was outdated, currently the active version is `@2`: https://github.com/actions/cache/releases
2. For some reason it was using `pyproject.toml` as a caching key, but this file does not exist. I've changed it to be https://github.com/python/devguide/blob/main/requirements.txt
Question: other repos have `dependabot.yml` job to update GitHub Actions. Do you need one? I can send another PR if it is going to be useful.
=> Fix`actions/cache` in `ci.yml`

documenting.rst
https://sphinx-doc.org/ doesn't seem to resolve, but https://www.sphinx-doc.org/ does
=> Added 'www' in front of links to sphinx-doc.org

buildbots.rst
Minor fix changing the CI service names referenced in buildbots.rst from AppVeyor and Travis which appear to have been replaced with GitHub Actions and Azure Pipelines for running tests on PRs.
=> Update CI service names referenced in buildbots.rst

communication.rst
* move the Diversity statement reference up to the top of the
page (it's getting a bit hidden as the earlier sections grow)
* add info on joining the Discord server
* expand on the usage of Discourse
* mention and link to the Mailman 3 web gateway
=> Communications: add Discord, expand on Discourse

c-api.rst, extensions.rst, index.rst, langchanges.rst, requirements.txt, stdlibchanges.rst, triaging.rst
With the recent implementation of [PEP 676](https://peps.python.org/pep-0676/) the canonical URL for PEPs has changed from, for example:
https://www.python.org/dev/peps/pep-0008/
to:
https://peps.python.org/pep-0008/
Redirects are in place so the old links still work, but let's update to use the new canonical form.
See also:
* [bpo-47126](https://bugs.python.org/issue47126) / https://github.com/python/cpython/pull/32124
* https://github.com/sphinx-doc/sphinx/pull/10267
=> Update to canonical PEP URLs

appendix.rst, committing.rst, communication.rst, coverage.rst, docquality.rst, fixingissues.rst, gh-faq.rst, gh-labels.rst, help.rst, index.rst, langchanges.rst, pullrequest.rst, setup.rst, silencewarnings.rst, stdlibchanges.rst, tracker.rst, triaging.rst
This change should be landed once issues are migrated from BPO to Github issues. Some information here is based on https://github.com/psf/gh-migration/issues/13 and PEP 588.
The bulk is in `tracker.rst` and `triaging.rst`. Since they must make sense in their entirety, I temporarily deleted the old versions of those files and created new ones so that they can be reviewed without confusing diffs.
=> Document using Github issues as the issue tracker

triaging.rst
As discussed on the CPython core-dev discord channel, there are several issues with the current policy that states that triagers should never close PRs:
- Github's setup allows members of the triage team to close PRs, regardless of the policy stated in the devguide.
- This policy isn't consistently followed by all members of the triage team. Some triagers occasionally close PRs (I have closed one or two myself in situations where it seemed abundantly clear that there was no prospect of the PR being merged).
- This policy isn't really enforced in any way if triagers do close PRs. This lack of enforcement seems to be an implicit endorsement of the idea that it is okay for triagers to close PRs in some circumstances.
- It feels silly to have to bother a core dev with a request for a PR to be …
=> Allow triagers to close PRs if the PR is of very low quality

runtests.rst
Original BPO: https://bugs.python.org/issue46425
Refs https://github.com/python/cpython/pull/30800 and https://github.com/python/cpython/pull/30799
CC @jaraco 🙂
=> Add a note about direct test module invocation

gh-faq.rst, gh-labels.rst, pullrequest.rst, triaging.rst
Single backticks are for Markdown.
And Github -> GitHub.
=> Use double backticks for code in RST

.github/workflows/ci.yml, appendix.rst, c-api.rst, committing.rst, compiler.rst, coverage.rst, documenting.rst, garbage_collector.rst, parser.rst, pullrequest.rst, runtests.rst, tracker.rst
PR https://github.com/python/devguide/pull/832 fixes some of the errors found by `make check`. ✅ 
However, the root problem: `make check` isn't run on the CI, so these things slip in.
And interestingly, it must have once run on the CI, because the [devguide says](https://devguide.python.org/docquality/#developer-s-guide-workflow):
> Note that make check runs automatically when you submit a [pull request](https://devguide.python.org/pullrequest/).
This PR:
* Includes PR https://github.com/python/devguide/pull/832 to fix `make check` whitespace errors
* Fixes the other `make check` errors: all cases of using single backticks instead of two for RST
* Run `make check` on the CI again, to prevent these
* Instead of repeating the other long commands on the CI, use the `make` commands (`make …
=> Run 'make check' on the CI

documenting.rst
related to [#835](https://github.com/python/devguide/issues/835)
=> Update Translators Table

buildworker.rst, c-api.rst, committing.rst, compiler.rst, docquality.rst, motivations.rst, tracker.rst
(some found via `make linkcheck`)
Related to https://github.com/python/devguide/issues/681
=> Fix some incorrect links

gh-labels.rst
[devguide page](https://devguide.python.org/gh-labels/#component) has it as 'documentation', while [cpython repo labels](https://github.com/python/cpython/labels/) have it as 'docs'
=> Change label to shortened form

gitbootcamp.rst, pullrequest.rst
If we add `gh-` prefix to each commits, many spammy notification send to the issue.
See this ecample:
We should recommend `gh-` prefix only in pull request title (and merge commit title).
=> Do not recommend to gh- prefix in commit message

runtests.rst
Fixes #280
The section pointing that tests can be run from IDLE using the below construct is no longer relevant as suggested in this [message](https://bugs.python.org/issue31761#msg304273):
```>>> from test import autotest```
Hence, this section was removed from the `Running & Writing Tests` section of the devguide.
=> removed reference of testing through IDLE

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, committing.rst, gh-faq.rst, index.rst, triaging.rst
Update old references to bugs.python.org to the new GitHub issue tracker.
Rather than linking directly to https://github.com/python/cpython/issues, I used https://devguide.python.org/tracker/ which has important info like to search for duplicates first.
=> Update links for new issue tracker

docquality.rst, documenting.rst
This PR documents the `htmlview` make target (added in #826) for both the `devguide` and `cpython` repos.
=> Document the `htmlview` make target.

Makefile
This PR:
* Updates the `venv` target
* Adds a `clean-venv` target
* Updates the `clean` target to call `clean-venv` too
These are copied from [`cpython/Doc/Makefile`](https://github.com/hugovk/cpython/blob/1ed8d035f1edfaec34016b9f8d615df9e9fe9414/Doc/Makefile#L150-L159) with minor changes.
See #854.
=> Update `venv` and `clean` make targets

documenting.rst
The Transifex link for the zh-tw translation seems to be obsolete since it only has the 3.6 docs.  The project has since moved to GitHub, so we can remove the link.
@mattwang44 can you confirm this is correct?
=> Remove obsolete zh-tw translations link

parser.rst
The script it should be referencing is https://github.com/python/cpython/blob/main/PCbuild/build.bat, as https://github.com/python/cpython/blob/main/PCbuild/python.bat doesn't exist.
=> Fix typo (`python.bat`->`build.bat`)

index.rst
fixes #613
The first paragraph of the `Quick References` section of the `Devguide` referenced the setup guide linked here(https://devguide.python.org/setup/#setup). This redundant reference is removed in this PR.
=> fixes #613: remove redundant references to setup guide

documenting.rst
This fixes a typo reported in GH-872 by rewording a sentence according to [PEP 545](https://peps.python.org/pep-0545/#add-translation-to-the-language-switcher).
=> gh-872: fix a typo and reword a sentence in the translating docs.

coverity.rst
After https://github.com/python/cpython/commit/0c21214f3e583d541227df2239de377e796b55fa removed `Py_VA_COPY` usage from the codebase leaving `#define Py_VA_COPY va_copy` behind, the *[Coverity Scan → Known limitations → Intentionally → Py_VA_COPY](https://devguide.python.org/coverity/#intentionally)* section became obsolete and can be removed.
=> Remove outdated ` Py_VA_COPY` Coverity false positive

setup.rst
When using WSL with Ubuntu, it was not obvious how to get the relevant deb-src to avoid error "E: You must put some 'deb-src' URIs in your sources.list".
The file already contained the urls which can be uncommented to continue the process of installing dependencies.
=> suggest edit of sources.list to enable deb-src's

pullrequest.rst, tracker.rst
where now we can opt to close as complete or not-planned.
GH issue: https://github.com/python/devguide/issues/870
GH blog:
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
=> gh-870 Added Closing PR section for close reasons

communication.rst, conf.py, help.rst
Fixing issue #853 updating documentation about usage of Discourse. 
Added info includes:
- brief overview of categories in discourse
- getting started
- tutorials for new users
- how to read topics and threads
- following and adding notifications in both categories and topics
- enabling mailing list mode
=> gh-853: Update Document Discourse.

setup.rst
I am using Mac OS Catalina 10.15.7.
To avoid getting the following warning : 
`configure: WARNING: pkg-config is missing. Some dependencies may not be detected correctly.`
`brew install pkg-config` needs to be run.
Issue number: https://github.com/python/cpython/issues/93658
=> Updating brew install command to avoid pkg-config warning

setup.rst
I am using Mac OS Catalina 10.15.7.
This is to avoid getting the following message:
> The necessary bits to build these optional modules were not found:
> _tkinter
The solution was provided by @erlend-aasland.
Issue number: https://github.com/python/cpython/issues/93659
=> Updating brew install command to build _tkinter

garbage_collector.rst
This PR fixes a typo as well as an incorrect capitalization.
=> Fix typo (double -> doubly)

setup.rst
I am using Mac OS Catalina 10.15.7.
To avoid getting the following messages : 
> The necessary bits to build these optional modules were not found:
> _hashlib              _ssl   
as well as:
> Could not build the ssl module!
> Python requires a OpenSSL 1.1.1 or newer
Based on the comments below, the solution is to indicate the OpenSSL version in the brew command: `brew install openssl@1.1` and make a note to update this line with `brew install openssl@3` when OpenSSL 3 is supported.
Initial (and outdated descritption below):
<details>
Running `brew install openssl@3` allowed the  _hashlib _ssl modules to build, but as suggested in a comment by @ezio-melotti it seemed strange that the version needed to be specified. 
I am therefore updating the documentation by leaving the suggested …
=> Building _hashlib and _ssl modules

gitbootcamp.rst
Deleted the duplicated paragraph "Committing Changes" (already in the paragraph "Staging and Committing Files") and changed "git add" to "git add -p". All accordingly to https://github.com/python/devguide/issues/888
=> Deleted duplicated paragraph

core-developers/experts.rst
`_dummy_thread` and `dummy_threading` modules are removed in https://github.com/python/cpython/pull/14143 so keep Experts Index in sync.
=> Remove dummy thread modules from Experts Index

testing/coverage.rst
This PR removes a sentence that no longer applies on account of the GitHub Issues transition. Issue authors can't apply labels, and the "tests" label is added automatically.
=> Remove sentence mooted by GitHub Issues transition

getting-started/setup-building.rst
The brew install command was updated in #892, but the corresponding commands were not.
=> Fix brew prefix passed to configure for openssl@1.1

documentation/markup.rst
This PR adds a quick reference table at the top of the rst reference page.  The goal of this table is to show some commonly used markup and to include links to the relevant sections.  I also added some internal references and changed a title.
This was proposed a decade ago on IRC, and then captured in https://github.com/python/cpython/issues/58426#issuecomment-1093572689 [^1]
[^1]: note that the issue itself (now transferred to #14) is probably obsolete, and this proposal doesn't aim to solve that.
=> Add a quick reference for rst markup.

index.rst
This link got removed in 7ab47a07ff686afa43621c130304fd42bce75f14 and it's not longer needed.
=> Removed unused reference.

developer-workflow/c-api.rst, testing/run-write-tests.rst
Here are some developer docs for C API tests (https://github.com/python/cpython/issues/93649 and https://github.com/python/cpython/issues/95991).
=> Document how to add C API tests

core-developers/become-core-developer.rst, core-developers/committing.rst, core-developers/experts.rst, core-developers/motivations.rst, core-developers/responsibilities.rst, developer-workflow/communication-channels.rst, developer-workflow/lang-changes.rst, developer-workflow/stdlib.rst, getting-started/getting-help.rst, getting-started/pull-request-lifecycle.rst, triage/issue-tracker.rst, triage/labels.rst, triage/triage-team.rst
As a followup to #938 , updates a number of additional references to and discussions of the mailing lists to prefer Discourse instead. In the process, as it particularly updated sections related to the PEP process, it elided a substantial amount of out of date material that duplicated both PEP 1 and between devguide documents describing mailing list/Discourse posting around such, focusing on the material unique/specific to each section while referring the rest to either the communication channels doc or the canonical source, PEP 1.
As part of this, this also clarifies, updates and improves existing references to Discourse, and revised its existing "Getting Help" section to avoid duplicating a fair amount of the material in the communication channels doc and focus on, well, "getting help" …
=> Point to Discourse instead of mailing lists as the nominal core dev discussion venue

versions.rst
As per https://www.python.org/downloads/release/python-3110rc2/ - I was looking up EOL dates, but it was a bit jarring to see 3.11 listed as already released 😅
=> Update expected release date of 3.11

requirements.txt
Between PR https://github.com/python/devguide/pull/954 being opened ([CI passed](https://github.com/python/devguide/actions/runs/3197379860)) and merged 25 minutes later ([CI failed](https://github.com/python/devguide/actions/runs/3197545797)), a [new release of sphinx-lint](https://pypi.org/project/sphinx-lint/0.6.2/) came out with differing checks.
Let's pin it to get the CI green, and I'll open an issue to upgrade and fix the issues.
=> Pin sphinx-lint to fix the CI

documentation/style-guide.rst, internals/parser.rst, testing/coverage.rst
This PR fixes  markup errors exposed by `sphinx-lint` `0.6.3`, even though two of them are actually false positives:
```
./venv/bin/sphinx-lint -i tools -i ./venv --enable default-role
testing/coverage.rst:262: default role used (hint: for inline literals, use double backticks) (default-role)
documentation/style-guide.rst:154: default role used (hint: for inline literals, use double backticks) (default-role)
internals/parser.rst:836: default role used (hint: for inline literals, use double backticks) (default-role)
internals/parser.rst:837: default role used (hint: for inline literals, use double backticks) (default-role)
internals/parser.rst:838: default role used (hint: for inline literals, use double backticks) (default-role)
```
See also:
* #956 
* …
=> Fix some markup (including 2 false-positives).

.readthedocs.yml
Similar to https://github.com/python/peps/pull/2728.
ReadTheDocs now has a beta feature to override the build commands:
* https://twitter.com/readthedocs/status/1549145303801946112
* https://docs.readthedocs.io/en/latest/build-customization.html#override-the-build-process
Right now, a whole bunch of dependencies are installed that we don't use.
This can be slow especially as some old dependencies are built from source because they don't support modern Python and don't have wheels available (e.g. https://github.com/readthedocs/readthedocs.org/issues/9118).
Instead, we can just `make html` to only install the stuff we need.
This speeds up the command-running time from ~61 to ~22 seconds (the upload is a constant ~30s in both cases).
Each build step took:
1. Command time: 0s
2. Command time: …
=> Override RTD build commands to speed up docs build

_extensions/custom_roles.py, conf.py, triage/labels.rst
This adds a `:gh-label:` role to link to a GitHub label on https://github.com/python/cpython.
For example:
* ``` `:gh-label:`docs` ``` -> `https://github.com/python/cpython/issues?q=is%3Aopen+sort%3Aupdated-desc+label%3Adocs`
* ``` :gh-label:`skip news` ``` -> `https://github.com/python/cpython/issues?q=is%3Aopen+sort%3Aupdated-desc+label%3A%22skip+news%22`
This makes it easy to click through to see recent examples of the actual label in use.
It also helps https://github.com/python/devguide/issues/821 because we can click through and find which labels have since been deleted (e.g. `invalid`) or renamed (`library`).
=> Add a Sphinx role to link to GitHub labels

.github/workflows/ci.yml, conf.py, getting-started/setup-building.rst
For blocks showing commands, where there's output shown, it's best to show a `$` prompt and use `console` formatting, so they're shown with formatting:
```console
$ git remote -v
origin  git@github.com:<your-username>/cpython.git (fetch)
origin  git@github.com:<your-username>/cpython.git (push)
upstream        git@github.com:python/cpython.git (fetch)
upstream        git@github.com:python/cpython.git (push)
```
(These PR message examples are shown in Markdown because GitHub, but a similar thing applies to RST in the devguide.)
If there's no output shown, instead of `console` formatting and a prompt, it's better to use `bash` without a prompt.
Here's an example with `console` and prompts:
```console
$ # In the CPython root:
$ docker run -v$(pwd):/src:Z -w /src --rm -it ubuntu:22.04 \
bash …
```
=> Setup and Building: update code blocks

core-developers/committing.rst, triage/triaging.rst
This PR updates the `triage/triaging.rst` page, which contained outdated references to bpo and HG's patch-based workflow.
See https://cpython-devguide--914.org.readthedocs.build/triage/triaging/
=> Update the triage/triaging.rst page.

.readthedocs.yml
Follow on from https://github.com/python/devguide/pull/933, we should use the dirhtml builder instead of html, so the redirects work as before.
Example redirect:
* https://cpython-devguide--965.org.readthedocs.build/pullrequest/ ➡️ https://cpython-devguide--965.org.readthedocs.build/getting-started/pull-request-lifecycle/index.html
=> Use dirhtml builder for Read the Docs

getting-started/setup-building.rst
This PR fixes #817. 
It uses homebrew's gdbm and xz.
=> Fix gdbm build on macos

Makefile
Similar to https://github.com/python/cpython/pull/98189, the list of phony targets in the `Makefile` had got out of sync with the commands: `clean-venv`, `venv`, `ensure-venv` and `serve` were missing.
I expect it will happen again because it's easy to copy and paste a target and not realise/remember to update the list of `.PHONY` targets at the top of the file.
Let's do as @zware suggested in https://github.com/python/cpython/pull/98189#issuecomment-1276664528 and put each one right next to its target.
We do this at [Pillow](https://github.com/python-pillow/Pillow/blob/main/Makefile) and at work, it helps a lot.
(See also https://github.com/python/cpython/pull/98266 to update the CPython docs Makefile.)
=> Move .PHONY to each section to avoid copy/paste omissions

getting-started/git-boot-camp.rst, getting-started/setup-building.rst
=> Prefer upstream for main

conf.py
For instance, the macOS build command
=> Fix copying of multiline snippets

getting-started/pull-request-lifecycle.rst
This isn't a particularly common issue but every now and then somebody will waste their time by preparing a change against a maintenance branch instead of working with `main` from the get-go.
This change serves as a reminder to contributors to think about the `main` branch first.
Key changes:
=> Explain that the contributors should base changes against `main`

_extensions/custom_roles.py, internals/parser.rst
This PR adds a role to link to GitHub files (in the `python/cpython` repo) and uses them in `internals/parser.rst`.
* Fixes #960
=> Add a Sphinx role to link to GitHub files 

getting-started/setup-building.rst
As originally brought up on the Core Dev Discord, problems will result when the build configuration/platform set in the Visual Studio IDE differs from that set on the command line with the `PCBuild/build.bat` script, and in fact the current defaults are opposite one another (`Debug` and `Win32` for the former, and `Release` and `x64` for the latter). Furthermore, it was noted that the [current Windows section in the Setup and Build doc](https://devguide.python.org/getting-started/setup-building/#windows), the listed invocation of the `build.bat` script uses the `Release` configuration, when in fact the `Debug` config is what users developing CPython are likely to want and also doesn't match the default in VS. Finally, it was also noted that the section never specifies how to actually …
=> Refine Windows build section, explain config & add how to run

developer-workflow/c-api.rst
Build definitions need to be updated -- see e.g.
https://github.com/python/cpython/pull/99549
https://github.com/python/cpython/pull/95819
https://github.com/python/cpython/pull/99494
=> Add missing step to C API tests instructions

versions.rst
Follow on from https://github.com/python/devguide/pull/988.
Visit https://devguide.python.org/versions/.
---
---
---
Instead, hide chart code and advise the user to enable JS if they wish to see the chart:
Uses the advice at https://florianbrinkmann.com/en/css-rules-when-javascript-is-disabled-4536/
---
https://cpython-devguide--997.org.readthedocs.build/versions/
=> Release cycle chart: show suggestion if JavaScript disabled

getting-started/getting-help.rst
For the second point of https://github.com/python/core-workflow/issues/457.
Zulip is no longer used and there's very little activity:
The little activity that remains is unanswered questions, such as:
There are better places to ask for help, let's remove Zulip references from the devguide.
Ping also @Mariatta as it referred to your Office Hour, but I see there was no activity for a few years so I think we're fine to remove it, unless you'd like to replace it with something else.
=> Remove reference to unused Zulip chat

documentation/translating.rst, getting-started/git-boot-camp.rst, getting-started/pull-request-lifecycle.rst, getting-started/setup-building.rst, index.rst, internals/compiler.rst, testing/coverage.rst, triage/github-bpo-faq.rst, triage/labels.rst
For https://github.com/python/devguide/issues/681.
* Update link redirects
* Remove link on homepage to old Roundup meta tracker
=> Update link redirects

conf.py, getting-started/pull-request-lifecycle.rst
For #681.
* Group `linkcheck_*` configs together
* Update `linkcheck_ignore` rules
* Add `linkcheck_allowed_redirects` rules
* Update new PSF link redirect
Linkcheck docs: https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder
After this (and https://github.com/python/devguide/pull/1001 and https://github.com/python/devguide/pull/1002), all that fails with `make linkcheck` are the four tracked in https://github.com/python/devguide/issues/1003.
=> Ignore broken links and allow redirects

getting-started/setup-building.rst
Follow on from https://github.com/python/devguide/pull/995.
---
Apple currently supports macOS 11 (released Nov 2020), 12 (Oct 2021) and 13 (Oct 2022).
The older "Mac OS X" and "OS X" are all long out of support.
* https://en.wikipedia.org/wiki/MacOS#Release_history
---
We have [one section](https://devguide.python.org/getting-started/setup-building/#macos) specifically with two sets of instructions:
* older set: Mac OS X (versions 10.0-10.7) and OS X (10.8)
* newer set: OS X (10.9-10.11) and macOS (versions 10.12+)
It's good to differentiate the names here, but let's remove the instructions for the older set:
* Mac OS X versions 10.0-10.7 were released between 2001-2012
* OS X 10.8 was released between 2012-2015
And also for OS X in the newer set:
* OS X versions 10.9-10.11 were released …
=> Remove old Mac OS X (10.0-10.7) and OS X (10.8-10.11) info

advanced-tools/gdb.rst
For https://github.com/python/devguide/issues/681.
```console
$ make linkcheck | grep broken
(developer-workflow/grammar: line   40) broken    https://github.com/python/cpython/blob/main/Include/Python-ast.h - 404 Client Error: Not Found for url: https://github.com/python/cpython/blob/main/Include/Python-ast.h
(internals/compiler: line  516) broken    https://github.com/python/cpython/blob/main/Include/code.h - 404 Client Error: Not Found for url: https://github.com/python/cpython/blob/main/Include/code.h
(developer-workflow/grammar: line   33) broken    https://github.com/python/cpython/blob/main/Include/token.h - 404 Client Error: Not Found for url: https://github.com/python/cpython/blob/main/Include/token.h
(internals/compiler: line  488) broken …
```
=> Fix a broken link

core-developers/become-core-developer.rst
During my recent experience nominating someone for commit privileges, I ran into some friction attempting to follow the guidance. This change addresses that friction.
- Allow the audience to be anybody (not just an individual seeking commit privileges). Avoids use of second-person language.
- Provide guidance for all involved.
- Refer to the various actors directly, avoiding passive language. Use 'candidate', 'submitter', and 'approver' to represent the key actors.
- Move the "cross-post" action into step 1 to indicate better the temporal positition of the action.
- Summarize the confirmation criterion (2/3 vote) rather than make the reader go to the PEP, which basically indicates 2/3 vote.
- Include the steering council email, because the submitter may not know it.
- Normalize the …
=> Refine 'gaining commit privileges'.

developer-workflow/grammar.rst, internals/compiler.rst
This PR fixes the remaining broken links and closes #681.
=> Fix remaining broken links.

documentation/markup.rst
Extra backtick is causing a ref to show as emphasys instead of the expected link to a target.
A screenshot from [Directives](https://devguide.python.org/documentation/markup/#directives):
=> Fix a ref markup syntax in markup.rst

index.rst
These "Moved to [another-page#another-anchor]" links are a convenience to avoid linkrot:
---
Like at https://devguide.python.org/documentation/start-documenting/#style-guide, let's put them at end of the page.
So when reading through a page, the reader is not disturbed by a notice that some content has moved.
---
Before: https://devguide.python.org/#status-of-python-branches
After: https://cpython-devguide--1015.org.readthedocs.build/#status-of-python-branches
=> Move 'moved to' link to the end

documentation/help-documenting.rst
Update redundant BPO info now we're using GitHub issues.
---
I'm not sure if we still need this bullet point?
```diff
-* check to see if there is a paperclip or `octocat`_ icon at the end of the
-  issue's title column.  If there is, then someone has already created a pull
+* check to see if there is pull request icon to the right of the
+  issue's title.  If there is, then someone has already created a pull
request for the issue.
```
=> Helping with Documentation: Update old BPO info

triage/labels.rst
There was a bit of confusion on a recent PR whether contributors can add labels to issues and PRs.
Let's make explicit that only triagers, core devs and bots can.
=> Make clear who can add labels on GitHub

getting-started/pull-request-lifecycle.rst
`patchcheck.py`, `reindent.py` are moved from `Tools\scripts\` to `Tools\patchcheck\`
Ref: https://github.com/python/cpython/pull/98186
`reindent-rst.py` are deleted.
whitespaces in docs are handled by `patchcheck.py` itself
Ref: https://github.com/python/cpython/pull/97675
=> Update `patchcheck` description

internals/garbage-collector.rst
=> Consistently use 'gc_ref' in the garbage collector docs

index.rst
They're both popular and important, so they belong in the list of other Python implementations.
=> Mention MicroPython and CircuitPython in other implementations.

developer-workflow/development-cycle.rst
This is a result of the discussion started by the 2022 Python Steering Council on https://discuss.python.org/t/new-python-organization-repository-policy/17376 and
https://mail.python.org/archives/list/python-dev@python.org/message/FAASOMUNQZDJBCOTZK6I2KH55SDOONF6/.
Petr's text from the discuss thread is used, omitting any mention of the PSF Contributor Agreement (CLA) as discussion revealed that it may not make sense for all repos (see thread).
It also adopts a suggestion from Joannah to have people discuss additions in our Committers forum before bringing an addition to the Python Steering Council.
=> Update the Org Repository Policy per the 2022 PSC

conf.py, requirements.txt
Use https://github.com/readthedocs/sphinx-notfound-page to create a 404 page with our theme, and also menu, so users can hopefully find their way more easily.
Docs: https://sphinx-notfound-page.readthedocs.io/
https://devguide.python.org/bleep-bloop
https://cpython-devguide--1042.org.readthedocs.build/bleep-bloop
=> Use sphinx-notfound-page to create a 404 page matching the theme

core-developers/committing.rst
Used at least on https://blurb-it.herokuapp.com/: 
> [add a blurb](https://devguide.python.org/committing/#what-s-new-and-news-entries) to CPython pull request.
=> Restore `#what-s-new-and-news-entries` anchor

core-developers/committing.rst
=> Clarify that local time is used in NEWS entry blurb titles

getting-started/setup-building.rst
I've fixed the link in Victor Stinner's guide.
File: getting-started/setup-building.rst
Line number: 317
=> Use Wayback Machine link for defunct Victor Stinner's guide #1048

advanced-tools/gdb.rst, conf.py, getting-started/setup-building.rst
Fixes #1044
1.   In ``advanced-tools/gdb.rst`` there was a broken link under the topic of [GDB 7 and later](https://devguide.python.org/advanced-tools/gdb/#gdb-7-and-later) which was named as _extending gdb with Python_ ``https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html#Python`` which has now been replaced by the following link ``https://sourceware.org/gdb/onlinedocs/gdb/Python.html``
2. In ``conf.py`` there was a _slash_  at the end of the link ``https://github.com/python/voters/`` which made this link broken and this issue has been resolved by removing the _slash_ from the end of the link ``https://github.com/python/voters``
=> Update gdb & Victor's guide links, and fix voters link ignore

getting-started/setup-building.rst
1. Update the command for building Python 3.7 through 3.9 by exporting `PKG_CONFIG_PATH` so `pkg-config` can find `tcl` and `tk`
2. Instruct users on installing `openssl` with `brew` for building Python 3.10
Fixes: #1049
Signed-off-by: César Román <thecesrom@gmail.com>
=> Update instructions for building on macOS

conf.py
Similar to https://github.com/python/python-docs-theme/pull/108.
Fix the problems we saw at https://github.com/python/devguide/pull/1034#issuecomment-1411782361 when the CSS file changed but browsers kept the old version cached for 24 hours.
Append a `?digest=hash` to the end of the `pydoctheme.css`, computed from the file contents, so when a new CSS file is deployed, the old one is no longer used from the browser cache.
For example:
`<link rel="stylesheet" type="text/css" href="_static/devguide_overrides.css?digest=951d6a16b747d96c03796069dbeb516764307ae2" />`
This is based on how @pradyunsg's Furo theme does it:
https://github.com/pradyunsg/furo/blob/193643fdb6787501195555244f4a9e953ef544bb/src/furo/__init__.py#L149-L161
Thanks @pradyunsg!
View the source of pages at …
=> Append a hash ?digest to CSS files for cache-busting

.github/workflows/documentation-links.yml
Once merged, this will automatically add a docs preview link to PRs.
> GitHub Action that automatically edits Pull Requests' descriptions with a link to documentation's preview on Read the Docs.
https://github.com/readthedocs/actions/tree/v1/preview
For example: https://github.com/python/docs-community/pull/75
=> Automatically edit PRs with link to RTD preview

documentation/start-documenting.rst
As discussed in #1037 , the [Building the documentation section](https://devguide.python.org/documentation/start-documenting/#building-the-documentation) is potentially confusing and difficult to follow to a new contributor (i.e. the primary target audience), as it lacks a clear, concrete, step by step structure, muddles minor or advanced details and elaboration with key basic information, and has some out of date information (sphinx-build, dependency names/versions, third-party virtualenv, etc), which also isn't in keeping with the [Diataxis principles for guides](https://diataxis.fr/how-to-guides/) like this.
Furthermore, as @peterjpxie mentioned, it manually lists certain dependencies and states that they are required to be installed no less than three times (including twice in the …
=> Overhaul Building the Documentation section for clarity

core-developers/experts.rst
I talked to @ericvsmith and confirmed that he is OK with me joining him in the dataclasses experts list.
----
:books: Documentation preview :books:: https://cpython-devguide--1063.org.readthedocs.build/
=> add carljm to experts index

documentation/markup.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1064.org.readthedocs.build/
=> Tiny editorial nit: extra single quote

versions.rst
Setting `:widths:` leads to weird wrapping, as some columns are too narrow. Just letting Sphinx figure it out, OTOH, looks fine. Let the software be smart.
Signed-off-by: FeRD (Frank Dana) <ferdnyc@gmail.com>
=> Don't force table widths in versions.rst

documentation/translating.rst
Add Atsuo Ishimoto as an additional coordinator of the Japanese translation team.
https://discuss.python.org/t/volunteering-to-be-a-coordinator-of-the-japanese-translation-team/25238
----
:books: Documentation preview :books:: https://cpython-devguide--1070.org.readthedocs.build/
=> Add Atsuo Ishimoto to the Japanese translation team

core-developers/experts.rst
This includes things like https://github.com/python/cpython/pull/102222 which currently does not has an obvious expert entry. 
----
:books: Documentation preview :books:: https://cpython-devguide--1068.org.readthedocs.build/
=> Add experts for runtime lifecycle management

triage/labels.rst
For https://github.com/python/core-workflow/issues/450.
To merge once labels are renamed for https://github.com/python/core-workflow/issues/450#issuecomment-1509743345.
New name and anchor:
* https://cpython-devguide--1076.org.readthedocs.build/triage/labels/#topic-labels
Keep the old anchor pointing to the same bit:
* https://cpython-devguide--1076.org.readthedocs.build/triage/labels/#expert-labels
----
:books: Documentation preview :books:: https://cpython-devguide--1076.org.readthedocs.build
=> Rename expert labels to topic labels

triage/labels.rst
Removed the "automerge" label : 
changes : 
Removed the automerge label from the Triage > Labels page https://devguide.python.org/triage/labels/
closes issue #1080
----
:books: Documentation preview :books:: https://cpython-devguide--1082.org.readthedocs.build/
=> Removed "automerge" label

core-developers/committing.rst, getting-started/git-boot-camp.rst
Fixes #1079
----
:books: Documentation preview :books:: https://cpython-devguide--1084.org.readthedocs.build/
=> Document auto-merge

getting-started/git-boot-camp.rst
Followup to #1084
----
:books: Documentation preview :books:: https://cpython-devguide--1085.org.readthedocs.build/
=> Minor corrections to instructions regarding automerge

core-developers/experts.rst
* `asynchat`, `asyncore` and `smtpd` were removed in 3.12 by PEP 594 "Removing dead batteries from the standard library" https://peps.python.org/pep-0594/#deprecated-modules
* `binhex` was removed in 3.11 https://github.com/python/cpython/issues/89248
* `formatter` was removed in 3.10 https://github.com/python/cpython/issues/86465
* `imp` was removed in 3.12 https://github.com/python/cpython/pull/98573
* `symbol` was removed in 3.10 https://github.com/python/cpython/issues/85111
----
:books: Documentation preview :books:: https://cpython-devguide--1088.org.readthedocs.build/
=> Experts Index: Remove deleted modules

README.rst, _tools/generate_release_cycle.py
`datetime.datetime.utcnow` raises a deprecation warning in Python 3.12: https://github.com/python/cpython/issues/103857.
`datetime.UTC` is new in 3.11, and is an alias of `datetime.timezone.utc`, but I think we're fine requiring 3.11+ here.
https://docs.python.org/3/library/datetime.html#datetime.UTC
----
:books: Documentation preview :books:: https://cpython-devguide--1097.org.readthedocs.build/
=> Replace deprecated utcnow() with now(UTC)

core-developers/experts.rst
We support Android, as best-effort, I believe. I don't think we have anyone leading it though, right?
=> Add Android platform to the experts list

_static/devguide_overrides.css, include/release-cycle.json, versions.rst
We don't have a PEP for 3.13 yet, so I left it pointing to the 3.12 PEP for now.
For first release, I put the first Monday in October 2024. We can adjust when we know the real date.
----
:books: Documentation preview :books:: https://cpython-devguide--1099.org.readthedocs.build/versions/
=> Python 3.13 is now main

getting-started/setup-building.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1104.org.readthedocs.build/
=> Add note about the CI generated ABI file

README.rst, _tools/generate_release_cycle.py
Re: https://github.com/python/devguide/pull/1097#issuecomment-1574641062
Let's maintain support for Python versions earlier than 3.11.
Done as an `if/else` rather than a long ternary, as tools like pyupgrade can automatically remove the old code when the time comes.
----
:books: Documentation preview :books:: https://cpython-devguide--1107.org.readthedocs.build/
=> Maintain support for pre-Python 3.11

getting-started/setup-building.rst
Fixes #1111 
----
:books: Documentation preview :books:: https://cpython-devguide--1112.org.readthedocs.build/
=> Bump macOS build recommendations to OpenSSL v3.0

getting-started/setup-building.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1110.org.readthedocs.build/
=> Update build status message in the Setup/Building section

getting-started/setup-building.rst
Instead of talking a lot about how to regenerate `configure` using GNU Autotools, first recommend what we really want people to do: use `make regen-configure`. Second, mention that it's possible to run Christian's containers to regenerate configure. Lastly, talk briefly about regenerating using autotools directly. (IMO, we should remove that last bit; we just want people to use the containers.)
----
:books: Documentation preview :books:: https://cpython-devguide--1109.org.readthedocs.build/
=> Rewrite 'Regenerating configure' section of building guide

getting-started/git-boot-camp.rst
As described in the title, merely a aesthetic change.
First contribution here, so lemme know if I've messed something up!
----
:books: Documentation preview :books:: https://cpython-devguide--1113.org.readthedocs.build/
=> Correct punctuation (add full stops)

documentation/translating.rst
Replaced the GH-Pages link with the Read the Docs link for Turkish.
----
:books: Documentation preview :books:: https://cpython-devguide--1114.org.readthedocs.build/
=> Replace GH-Pages with RTD for Turkish

getting-started/setup-building.rst
Python 3.5 went EOL in 2020.
https://devguide.python.org/versions/#unsupported-versions
----
:books: Documentation preview :books:: https://cpython-devguide--1120.org.readthedocs.build/
=> Remove outdated reference to Python 3.5

documentation/help-documenting.rst
The Docs Discourse forum is the preferred way.
I reordered the sentence so that the discourse forum is mentioned first.
----
:books: Documentation preview :books:: https://cpython-devguide--1118.org.readthedocs.build/
=> Link to Discourse first in "Help with Documentation" section (take 2)

developer-workflow/c-api.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1123.org.readthedocs.build/
=> Add guidelines for C API return values

include/release-cycle.json
```console
$ pip install -U pepotron
...
$ pep 3.13
https://peps.python.org/pep-0719/
```
[PEP 719](https://peps.python.org/pep-0719/) has been published with the Python 3.13 schedule.
----
:books: Documentation preview :books:: https://cpython-devguide--1131.org.readthedocs.build/
=> Add PEP 719 for Python 3.13

include/release-cycle.json
Before the [PEP 719](https://peps.python.org/pep-0719/) schedule was published, we used the first Monday in October 2024 as a placeholder (https://github.com/python/devguide/pull/1099).
Let's update it to match the PEP.
----
:books: Documentation preview :books:: https://cpython-devguide--1132.org.readthedocs.build/
=> Update planned 3.13.0 release date: 2024-10-01

conf.py
Fixes #1141 
Added a space after $ so the leading space is not copied.
----
:books: Documentation preview :books:: https://cpython-devguide--1142.org.readthedocs.build/
=> Strip space from pasted text

getting-started/pull-request-lifecycle.rst
When reading through this section, I stumbled over the term "nosy list", not knowing what it means.
It seems to be a [legacy concept](https://devguide.python.org/triage/github-bpo-faq/#where-is-the-nosy-list),
so this PR rephrases it to fit in with existing GitHub [terminology](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues#stay-up-to-date).
=> Reviewing PRs: On GitHub the nosy list is called subscribers

getting-started/setup-building.rst
Hi, I'd like to add documentation to show how to use Codespaces for contributing to CPython with the [devcontainer](https://github.com/python/cpython/tree/main/.devcontainer) files Brett added. I've added the instructions at the bottom of the `Setup and Building` page. I initially added them as a separate page but thought this might be more appropriate. Feel free to let me know if you think they should live somewhere else.  
This is a PR that would solve https://github.com/python/devguide/issues/1138. I added some context about the discussions and places where some people had asked for docs in the issue. (Also sorry for the other closed PR's still getting used to contributing :)) 
----
:books: Documentation preview :books:: https://cpython-devguide--1144.org.readthedocs.build/
=> Adding Codespaces Documentation

documentation/translating.rst
Add myself as a new translating coordinator for zh_CN
----
:books: Documentation preview :books:: https://cpython-devguide--1150.org.readthedocs.build/
=> Add a new coordinator for zh_CN

testing/new-buildbot-worker.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1156.org.readthedocs.build/
=> Point to buildbot config repo rather than mailing list for adding a worker

testing/new-buildbot-worker.rst
:man_facepalming: check the URL *before* merge, not after.
----
:books: Documentation preview :books:: https://cpython-devguide--1157.org.readthedocs.build/
=> Fix buildbot config issue URL

conf.py, requirements.txt
This also removes ``_asset_hash()``, which is no longer needed.
A
----
:books: Documentation preview :books:: https://cpython-devguide--1155.org.readthedocs.build/
=> Bump Sphinx to 7.2.5

core-developers/motivations.rst, documentation/style-guide.rst, documentation/translating.rst, getting-started/git-boot-camp.rst, getting-started/pull-request-lifecycle.rst, getting-started/setup-building.rst, index.rst, internals/parser.rst, testing/new-buildbot-worker.rst
Following the [devguide style guide](https://devguide.python.org/documentation/style-guide/#capitalization):
* unicode -> Unicode
* UNIX -> Unix
Also:
* git -> Git when the proper noun (not changing `git` the command)
* lower case and upper case -> lowercase and uppercase (more common in CPython docs, also according to Microsoft and Red Hat style guides)
----
:books: Documentation preview :books:: https://cpython-devguide--1163.org.readthedocs.build/
=> Fix typos to follow style guide

core-developers/become-core-developer.rst, core-developers/motivations.rst, developer-workflow/communication-channels.rst
The [python-committers](https://mail.python.org/mailman3/lists/python-committers.python.org/) mailing list is read-only after being closed in favour of discuss.python.org:
* https://github.com/python/steering-council/blob/main/updates/2023-07-steering-council-update.md#2023-07-17 
* https://mail.python.org/archives/list/python-committers@python.org/message/6WA76BWOJMQFPOJBSFAJABDXVGHOY732/
----
:books: Documentation preview :books:: https://cpython-devguide--1166.org.readthedocs.build/
=> Remove redundant references to python-committers

Makefile, conf.py
This will mean references will be checked regardless of how Sphinx is run.
A
----
:books: Documentation preview :books:: https://cpython-devguide--1170.org.readthedocs.build/
=> Enable nit-picky mode in ``conf.py``

developer-workflow/c-api.rst
Discussion: https://github.com/python/cpython/pull/108440#issuecomment-1699105964
----
:books: Documentation preview :books:: https://cpython-devguide--1158.org.readthedocs.build/
=> Clarify that PyUnstable macros use "PyUnstable" prefix

development-tools/clinic.rst
cc: @erlend-aasland; there were two commits that I've only just noticed weren't included in the earlier branch. Please may you rebase-merge this PR to include them?
A
----
:books: Documentation preview :books:: https://cpython-devguide--1167.org.readthedocs.build/
=> Update ``clinic.rst`` from CPython

testing/coverage.rst
It stopped working and was removed from CPython builds in https://github.com/python/cpython/issues/88054
Coverage.py will be removing the code soon.
----
:books: Documentation preview :books:: https://cpython-devguide--1173.org.readthedocs.build/
=> Remove mention of fullcoverage

documentation/markup.rst
Companion to https://github.com/python/cpython/pull/110292.
``cmdoption`` has been [deprecated](https://www.sphinx-doc.org/en/master/usage/domains/standard.html#directive-option) since [Sphinx 1.0 (2010)](https://pypi.org/project/Sphinx/1.0/).
----
:books: Documentation preview :books:: https://cpython-devguide--1176.org.readthedocs.build/
=> Avoid the deprecated `.. cmdoption::` directive

developer-workflow/development-cycle.rst, versions.rst
- Adds guidelines on what release cycles (where) should get backports of documentation and testing improvements. 
- #1168
- Maybe #1069(?)
<details>
<summary>Changes visualized:</summary>
<a href="https://cpython-devguide--1169.org.readthedocs.build/developer-workflow/development-cycle/#maintenance-branches">Dev. Cycle</a>
<a href="https://cpython-devguide--1169.org.readthedocs.build/versions/#status-key">Versions</a>
</details>
----
:books: Documentation preview :books:: https://cpython-devguide--1169.org.readthedocs.build/
=> Note when to backport changes

getting-started/pull-request-lifecycle.rst, internals/garbage-collector.rst, internals/parser.rst, testing/coverage.rst
This PR fixes the indentation of several blocks in the following pages:
* https://devguide.python.org/getting-started/pull-request-lifecycle/#patchcheck
* https://devguide.python.org/internals/garbage-collector/
* https://devguide.python.org/internals/parser/#verbose-mode
* https://devguide.python.org/testing/coverage/#install-coverage
These were incorrectly rendered as blockquotes as described in https://github.com/python/devguide/issues/1178.
----
:books: Documentation preview :books:: https://cpython-devguide--1181.org.readthedocs.build/
=> gh-1178: fix indentation in a few more pages.

development-tools/clinic.rst
This PR fixes the indentation of several blocks in the https://devguide.python.org/development-tools/clinic/ page that were rendered as `blockquote`s as described in https://github.com/python/devguide/issues/1178.
----
:books: Documentation preview :books:: https://cpython-devguide--1180.org.readthedocs.build/development-tools/clinic/
=> gh-1178: fix indentation in the argument clinic page.

testing/new-buildbot-worker.rst
This PR fixes the indentation of several blocks in the https://devguide.python.org/testing/new-buildbot-worker/ page that were rendered as `blockquote`s as described in #1178.
----
:books: Documentation preview :books:: https://cpython-devguide--1179.org.readthedocs.build/testing/new-buildbot-worker/
=> gh-1178: fix indentation in the buildbot page.

index.rst
Follow-up of #1183 -- fixes a similar error in `index.rst`.
----
:books: Documentation preview :books:: https://cpython-devguide--1184.org.readthedocs.build/
=> Fix wrongly indented nested list in `index.rst`.

triage/triaging.rst
Clarify the close step in the triage checklist. TIL from @erlend-aasland. 👍🏼 
----
:books: Documentation preview :books:: https://cpython-devguide--1186.org.readthedocs.build/
=> Clarify close as not planned for triage

triage/triage-team.rst
Another fix that I missed because it used a different type of bullet list.
----
:books: Documentation preview :books:: https://cpython-devguide--1189.org.readthedocs.build/
=> gh-1178: fix wrong indentation in nested list

core-developers/become-core-developer.rst
When adding new core devs, we can do some tidyup and remove them from the [triage team](https://github.com/orgs/python/teams?query=triage) (they could be in "Docs Triagers" or "Python triage").
Also a little tidy up: punctuate list items following this [Google style guide](https://developers.google.com/tech-writing/one/lists-and-tables#punctuate_items_appropriately), and add a link for convenience.
----
:books: Documentation preview :books:: https://cpython-devguide--1191.org.readthedocs.build/
=> Update checklist: remove new core devs from triage team

testing/run-write-tests.rst
Closes #874 
----
:books: Documentation preview :books:: https://cpython-devguide--1187.org.readthedocs.build/
=> Add recommended locales to the testing document

internals/exploring.rst, internals/index.rst
- Add intro to index doc in internals section
- Reduce the toctree level displayed for better readability
- Add links to CPython references in source code layout file
- Edit prose in exploring the source code file
This is 1 of 3 PRs to update the internals documentation.
----
:books: Documentation preview :books:: https://cpython-devguide--1192.org.readthedocs.build/
=> Update internals section index and source code doc

internals/garbage-collector.rst, internals/parser.rst
- Move the author to a document history block at the end of the parser and GC docs
This is the second of three CPython Internals PRs.
----
:books: Documentation preview :books:: https://cpython-devguide--1193.org.readthedocs.build/
=> Move author to a block at end of document for CPython Internals docs on parser and GC

internals/compiler.rst, internals/interpreter.rst
Closes #1159 
- Updates the Compiler doc
- Moves content from Compiler doc to Interpreter doc
This is the third of three PRs about CPython Internals.
----
:books: Documentation preview :books:: https://cpython-devguide--1188.org.readthedocs.build/
=> Updating CPython Internals

core-developers/experts.rst
I've put myself against pydoc as an indication I'm interested in helping rather than claiming immediate expertise -- but happy to remove.
A
----
:books: Documentation preview :books:: https://cpython-devguide--1199.org.readthedocs.build/
=> Add Adam Turner to the Experts Index

.github/workflows/ci.yml, .github/workflows/documentation-links.yml, .github/workflows/lint.yml
This linkcheck job hung and was going to take the full (6h?) time before I cancelled it after 5.5 hours!
https://github.com/python/devguide/actions/runs/6558353388/job/17811745428
Let's add a timeout. 10 minutes should be more than enough for these.
----
:books: Documentation preview :books:: https://cpython-devguide--1200.org.readthedocs.build/
=> Add timeout to CI jobs

core-developers/experts.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1198.org.readthedocs.build/
=> Remove Distutils from the experts index

getting-started/pull-request-lifecycle.rst
Quoting PowerShell: `The term 'python.bat' is not recognized as the name of a cmdlet, function, script file, or operable program.`
`.\python.bat` however works perfectly.
----
:books: Documentation preview :books:: https://cpython-devguide--1202.org.readthedocs.build/
=> Fix PowerShell command

index.rst
I think it will make life a little easier for first time contributors.
----
:books: Documentation preview :books:: https://cpython-devguide--1195.org.readthedocs.build/
=> gh-1194: Add Windows command for patchcheck to Quick Reference

conf.py, index.rst, requirements.txt
This is for work on #1196
This PR introduces a new dependency: [sphinx-inline-tabs](https://sphinx-inline-tabs.readthedocs.io/en/latest/)
There were two design decisions I am not set on:
1. Should we say "Unix" or "Linux"? I picked "Unix" because the [setup docs](https://devguide.python.org/getting-started/setup-building/#mac-python-exe) say "Unix".
2. Is the most useful order Unix, then macOS, then Windows. I would presume most developers are using macOS, but other examples I've seen start with "Linux" (e.g., [PyPI](https://pip.pypa.io/en/stable/installation/), [Pillow](https://pillow.readthedocs.io/en/stable/installation.html#basic-installation)), so I put "Unix" first.
----
:books: Documentation preview :books:: https://cpython-devguide--1205.org.readthedocs.build/
=> Add inline tabs on Quick Reference page for commands on different systems

Makefile
Reduce duplication by making many targets set a `BUILDER` variable and call the main `html` target.
This also makes it more similar to the [CPython Docs](https://github.com/python/cpython/blob/main/Doc/Makefile) and [PEPs](https://github.com/python/peps/blob/main/Makefile) `Makefile`s, and makes things easier for us to maintain.
---
Also remove some redundant `echo`es. On `main`, `make html` ends like:
```
build succeeded.
The HTML pages are in _build/html.
Build finished. The HTML pages are in _build/html.
```
We don't need that extra final line. With this PR:
```
build succeeded.
The HTML pages are in _build/html.
```
Note: I left some `echo`es in there for some (unused?) targets like `make man` that don't finish building.
----
:books: Documentation preview :books:: …
=> Refactor `Makefile` to re-use targets via variables

Makefile, requirements.txt
Add a `make autobuild` target to use https://github.com/executablebooks/sphinx-autobuild.
When you run it, it builds the docs and serves them at something like http://127.0.0.1:8000/
You can visit any page, for example http://127.0.0.1:8000/documentation/style-guide.html, and when you edit/save your source `.rst` file, it will automatically rebuild and update the page in the browser.
This drastically improves the edit/inspect loop. A very nice touch is it will also keep you at the same position in the page.
Compare before:
1. switch to IDE: edit, save
2. switch to prompt: `make html`
3. switch to browser: reload, inspect
4. repeat
To this PR:
1. switch to IDE: edit, save
2. ~switch to prompt: `make html`~
3. switch to browser: ~reload,~ inspect
4. repeat
We can add the same thing to …
=> Add `make autobuild` to rebuild and reload HTML files in your browser

Makefile
Follow on from https://github.com/python/devguide/pull/1208.
Naming things: After using this more, I think it is better as `make htmllive`, as you can do `make html<TAB>` and see the various related options:
```console
❯ make html
html      htmlhelp  htmllive  htmlview
```
----
:books: Documentation preview :books:: https://cpython-devguide--1212.org.readthedocs.build/
=> Rename 'make autobuild' to 'make htmllive'

documentation/markup.rst
updated the doc by removing unused prompt
----
:books: Documentation preview :books:: https://cpython-devguide--1210.org.readthedocs.build/
=>  omitting the "unused" prompt in code example

triage/issue-tracker.rst
Use www.roundup-trcker.org rather than roundup.sourceforge.io.
----
:books: Documentation preview :books:: https://cpython-devguide--1213.org.readthedocs.build/
=> Update issue-tracker.rst - change Roundup link to canonical link

triage/issue-tracker.rst
When reviewing #1212, I noticed that we could be a bit clearer in the note about the historical tracker. 
----
:books: Documentation preview :books:: https://cpython-devguide--1214.org.readthedocs.build/
=> Add a URL for bpo and clarify historical tracker in note

development-tools/clinic.rst
See also https://github.com/python/cpython/issues/111903.
----
:books: Documentation preview :books:: https://cpython-devguide--1217.org.readthedocs.build/
=> Add "how to" for the critical_section Argument Clinic directive.

documentation/devguide.rst, documentation/start-documenting.rst
As suggested on [Discuss](https://discuss.python.org/t/make-htmllive-new-docs-makefile-target-for-easier-editing/38574/2?u=hugovk).
Use the same "Tip" infobox on the pages for CPython docs and for the devguide.
Note, I didn’t add `htmllive` to `make.bat` because I don’t have Windows to test it. Would a Windows user like to add the equivalent commands to `make.bat`, so we can remove the "(Unix only)"? I’d suggest here for the devguide first.
----
:books: Documentation preview :books:: https://cpython-devguide--1219.org.readthedocs.build/
=> Document 'make htmllive'

testing/new-buildbot-worker.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1221.org.readthedocs.build/
=> Document `keepalive` for buildbot workers may be the reason for frequent disconnects

documentation/translating.rst
This adds sphinx-lint to the list of tools used for translation. It is useful to find reST syntax issues in translation files that not reported by sphinx-build output.
----
:books: Documentation preview :books:: https://cpython-devguide--1230.org.readthedocs.build/
=> Mention sphinx-lint in the translation tools

documentation/devguide.rst
Hey again team! I was hoping to knock a few more of these out this weekend.
This PR should close a single TODO in #1196.
I did restructure the writing a bit to break up the directive "to build the devguide..." from the long paragraph before it.
----
:books: Documentation preview :books:: https://cpython-devguide--1223.org.readthedocs.build/documentation/devguide/
=> Add inline tabs on Helping with the Developer’s Guide page for commands on different systems

getting-started/git-boot-camp.rst
This PR should close a single TODO in https://github.com/python/devguide/issues/1196.
----
:books: Documentation preview :books:: https://cpython-devguide--1225.org.readthedocs.build/getting-started/git-boot-camp/
=> Add inline tabs on Git Bootcamp page for commands on different systems

documentation/start-documenting.rst
This PR should close a single TODO in https://github.com/python/devguide/issues/1196.
There is a little bit of discussion in the [Build using make / make.bat](https://devguide.python.org/documentation/start-documenting/#build-using-make-make-bat) section. My understanding is the commands are the same so I didn't try to make tabs for them all, but we can adjust if you believe that's better.
----
:books: Documentation preview :books:: https://cpython-devguide--1224.org.readthedocs.build/documentation/start-documenting/
=> Add inline tabs on Documentation Getting Started page for commands on different systems

getting-started/setup-building.rst
This PR should close a single TODO in https://github.com/python/devguide/issues/1196.
This page is a little more complicated than the previous others.
[Compile and build](https://devguide.python.org/getting-started/setup-building/#compile-and-build) has a long list of instructions that are the same for Unix and macOS, so I chose to group them under a single tab rather than duplicate them.
[Install dependencies](https://devguide.python.org/getting-started/setup-building/#install-dependencies) directly refers to "Linux" which is different than the "Unix" we've been using in the other pages. I decided to change the tab to a consistent "Unix" but left the rest of the section unchanged.
----
:books: Documentation preview :books:: https://cpython-devguide--1226.org.readthedocs.build/getting-star …
=> Add inline tabs on Setup and Building page for commands on different systems

testing/coverage.rst
This PR should close a single TODO in https://github.com/python/devguide/issues/1196.
----
:books: Documentation preview :books:: https://cpython-devguide--1228.org.readthedocs.build/testing/coverage/
=> Add inline tabs on Increase Test Coverage page for commands on different systems

documentation/style-guide.rst, internals/parser.rst
This is often written "C-API" but "C API" is both more common and used at https://docs.python.org/3/c-api/
In the CPython repo:
```console
❯ rg "C API" | wc -l
1039
❯ rg "C-API" | wc -l
69
```
In the devguide (before this PR fixes the lone "C-API"):
```console
❯ rg "C API" | wc -l
25
❯ rg "C-API" | wc -l
1
```
----
:books: Documentation preview :books:: https://cpython-devguide--1222.org.readthedocs.build/documentation/style-guide/#capitalization
=> Add 'C API' to the style guide

Makefile
This PR adds `-j auto` to the `Makefile`.
I found out that it was missing while working on https://github.com/sphinx-doc/sphinx/issues/10779, and after adding it the time required to build the devguide went down from 2.9s to 1.4s, so about twice as fast (this is on a 16-cores CPU).
----
:books: Documentation preview :books:: https://cpython-devguide--1220.org.readthedocs.build/
=> Add `-j auto` to the Makefile.

Makefile
When running `make htmllive`, this will open the browser when the docs have been built the first time. 
It means you don't need to hunt around for the link in:
```console
❯ make htmllive
venv already exists.
To recreate it, remove it first with `make clean-venv'.
Release cycle data generated.
./venv/bin/sphinx-autobuild -b html -d _build/doctrees  --re-ignore="/\.idea/|/venv/" . _build/html
[sphinx-autobuild] > sphinx-build -b html -d _build/doctrees /Users/hugo/github/devguide /Users/hugo/github/devguide/_build/html
Running Sphinx v7.2.6
matplotlib is not installed, social cards will not be generated
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 0 source files that are out of date
updating …
```
=> `make htmllive`: open browser when ready

getting-started/git-boot-camp.rst, index.rst
Makes it clear which are the good and bad examples.
✅ Doesn't rely on colour: colour blind people can still see a tick or cross 
✅ We don't rely on them: the good/bad meaning is still clear from the text
<details>
<summary>Details</summary>
</details>
<details>
<summary>Details</summary>
</details>
Compare, for example, the Google developer docs: https://developers.google.com/style/ui-elements
Also fix some formatting.
----
:books: Documentation preview :books:: https://cpython-devguide--1235.org.readthedocs.build/
=> Use emoji to illustrate good and bad example commit messages

getting-started/setup-building.rst
The `make regen-configure` does the right thing via containers already.
----
:books: Documentation preview :books:: https://cpython-devguide--1236.org.readthedocs.build/
=> Remove references to quay.io/tiran/cpython_autoconf

core-developers/experts.rst
Declare that I am interested in more things than just typing.py these days!
I've also taken the liberty of making changes to two other core devs' listed interests:
- I've listed @erlend-aasland as being interested in Argument Clinic
- I've listed @pfmoore as being interested in `ensurepip`.
@erlend-aasland, @pfmoore, are you okay with the changes to your listed interests? If not, I'll obviously revert those changes :)
----
:books: Documentation preview :books:: https://cpython-devguide--1240.org.readthedocs.build/
=> Updates to the experts index

core-developers/committing.rst, developer-workflow/communication-channels.rst, developer-workflow/development-cycle.rst, developer-workflow/stdlib.rst, documentation/markup.rst, getting-started/setup-building.rst, internals/parser.rst, testing/coverage.rst
Consistently use ^ iso. ' markups for subsubsections
----
:books: Documentation preview :books:: https://cpython-devguide--1239.org.readthedocs.build/
=> Lint: fixup subsubsection markups

core-developers/committing.rst, getting-started/setup-building.rst
- Add subsubsections instead of keeping all the text in a single large subsection
- Add some text about how to word NEWS entries
- Mention that test and strictly internal changes seldom require NEWS entries
(Some minor wording changes might have snuck in, but largely, I kept the existing text.)
----
:books: Documentation preview :books:: https://cpython-devguide--1238.org.readthedocs.build/core-developers/committing/#updating-news-and-what-s-new-in-python
=> Rework the docs for NEWS/What's New entries

development-tools/clinic.rst, development-tools/gdb.rst, getting-started/git-boot-camp.rst, testing/run-write-tests.rst
Fixes https://github.com/python/devguide/issues/661.
We've already removed quite a few other old ones, such as instructions for building older Python versions.
----
:books: Documentation preview :books:: https://cpython-devguide--1227.org.readthedocs.build/
=> Remove/update references to EOL Python versions

development-tools/clinic.rst
See: https://github.com/python/cpython/issues/112213
----
:books: Documentation preview :books:: https://cpython-devguide--1246.org.readthedocs.build/
=> Add explanation about @critical_section target directive

development-tools/clinic.rst
See: https://github.com/python/cpython/pull/112922
----
:books: Documentation preview :books:: https://cpython-devguide--1245.org.readthedocs.build/
=> Add "how to" for the setter Argument Clinic directive

developer-workflow/grammar.rst, internals/compiler.rst, internals/parser.rst
- Currently, the latest build (at the time of raising this PR) has the **typo** in `token.c` file, which can be seen here [`cpython-devguide--1245.org.readthedocs.build/`](https://cpython-devguide--1245.org.readthedocs.build/)
- Updated the name to point to the correct file
----
📚 Documentation preview 📚: https://cpython-devguide--1250.org.readthedocs.build/
=> Fix dead links to the tokenizer's source code

developer-workflow/index.rst, developer-workflow/sbom.rst
Part of https://github.com/python/cpython/issues/112302
Closes https://github.com/python/devguide/issues/1241
This adds an initial guide for maintaining CPython's SBOM document for core developers and adds a future location for the docs for later additions to CPython's SBOM tooling (e.g. when I implement external/optional dependencies from cpython-source-deps).
----
📚 Documentation preview 📚: https://cpython-devguide--1251.org.readthedocs.build/
=> Add initial guide for maintaining Software Bill-of-Materials

development-tools/clinic.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1248.org.readthedocs.build/
See: https://github.com/python/cpython/pull/113160
=> Add explanation about docstring for PyGetSetDef

conf.py, core-developers/motivations.rst, development-tools/gdb.rst, documentation/translating.rst
Fixes:
```
(core-developers/motivations: line  160) core-developers/motivations.rst:160: WARNING: redirect  http://www.bitdance.com - permanently to https://www.bitdance.com/
(core-developers/motivations: line  231) core-developers/motivations.rst:231: WARNING: redirect  http://www.list.org/ - permanently to https://www.list.org/
(developer-workflow/c-api: line   32) developer-workflow/c-api.rst:32: WARNING: redirect  https://discuss.python.org/c/30 - permanently to https://discuss.python.org/c/core-dev/c-api/30
(documentation/translating: line   53) documentation/translating.rst:53: WARNING: redirect  https://github.com/ftg-iran/python-docs-fa - permanently to https://github.com/mmdbalkhi/python-docs-fa
(testing/new-buildbot-worker: line   48) testing/new-buildbot-worker.rst:48: WARNING: …
```
=> Fix linkcheck warnings

triage/labels.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1259.org.readthedocs.build/
=> Document that type-feature labels do not need to be paired with version labels

documentation/style-guide.rst
Following https://github.com/python/cpython/pull/113695, document how to add big O notation.
----
📚 Documentation preview 📚: https://cpython-devguide--1261.org.readthedocs.build/documentation/style-guide/#big-o-notation
=> Add big O notation to the style guide

documentation/markup.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1264.org.readthedocs.build/
=> Clarify when to use versionadded and versionchanged

conf.py, developer-workflow/development-cycle.rst
I wasn't sure which page to put this, this one seems as good as any because there's also info about GitHub org owners and admins.
Maybe we should move it up the page too?
---
Related: https://github.com/capi-workgroup/decisions/ sticks out -- would the C API Working Group like to move inside the https://github.com/python/ org? (re: https://devguide.python.org/developer-workflow/development-cycle/#organization-owner-policy)
----
📚 Documentation preview 📚: https://cpython-devguide--1260.org.readthedocs.build/developer-workflow/development-cycle/#governance
=> Add governance contact

internals/garbage-collector.rst
This updates the garbage collector design page to describe the implementation of the GC for Python 3.13's free-threaded build.
----
📚 Documentation preview 📚: https://cpython-devguide--1263.org.readthedocs.build/
=> Describe GC for free-threaded build in the GC design doc

getting-started/git-boot-camp.rst
cherry_picker is in its own repo now.
----
📚 Documentation preview 📚: https://cpython-devguide--1274.org.readthedocs.build/
=> Remove reference to core-workflow

testing/coverage.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1276.org.readthedocs.build/testing/coverage/#using-test-regrtest
=> Replace BPO with GitHub links

development-tools/gdb.rst
GDB instructions have moved to the main CPython docs. We shouldn't keep a duplicate here.
This leaves two tips that aren't all that useful for extensions.
Fixes: #1278
----
📚 Documentation preview 📚: https://cpython-devguide--1279.org.readthedocs.build/
=> Replace most of "GDB Support" by a link to the main CPython docs

core-developers/experts.rst, triage/labels.rst
The experts list is perhaps not the best place for the Platforms table, but moving it is left to another PR.
I've removed the blank Android line in anticipation of PEP-738 getting accepted; if it doesn't make it I'll ask Malcolm to add it back with his name.
----
📚 Documentation preview 📚: https://cpython-devguide--1281.org.readthedocs.build/
=> Document the OS-Unsupported label and Platforms experts list

getting-started/setup-building.rst, index.rst
Fixes https://github.com/python/devguide/issues/1275.
https://devguide.python.org/#quick-reference says:
> See also [more detailed instructions](https://devguide.python.org/getting-started/setup-building/#compiling), [how to install and build dependencies](https://devguide.python.org/getting-started/setup-building/#build-dependencies), and the platform-specific pages for [Unix](https://devguide.python.org/getting-started/setup-building/#unix-compiling), [Install dependencies](https://devguide.python.org/getting-started/setup-building/#macos), and [Windows](https://devguide.python.org/getting-started/setup-building/#windows-compiling).
https://devguide.python.org/getting-started/setup-building/#macos says:
> This section explains how to install additional extensions (e.g. zlib) on …
=> Fix 'Install dependencies' links

documentation/style-guide.rst
Fixes https://github.com/python/docs-community/issues/109.
----
📚 Documentation preview 📚: https://cpython-devguide--1289.org.readthedocs.build/
=> Revise specific guidance about avoiding 'CPU'

documentation/markup.rst, documentation/style-guide.rst
I'm preparing to add more linguistic style to the style guide.  These two sections are about the logistics of .rst files, so I'm moving them to the markup page.
----
📚 Documentation preview 📚: https://cpython-devguide--1292.org.readthedocs.build/
=> Move markup concerns from style to markup

documentation/markup.rst
This is a better way to explain more about `literalinclude`
----
📚 Documentation preview 📚: https://cpython-devguide--1290.org.readthedocs.build/
=> Footnotes are discouraged

documentation/start-documenting.rst
The Style Guide and Translating sections I guess used to be on this page, but were moved.  We don't need these old placeholders anymore.
----
📚 Documentation preview 📚: https://cpython-devguide--1295.org.readthedocs.build/
=> No need for old redirect sections

README.rst, getting-started/setup-building.rst
Part of the PEP 730 work (python/cpython#114099).
Adds iOS details to the devguide. 
Also adds a note about htmlview and htmllive to the README, as they're too helpful to go hidden :-)
----
📚 Documentation preview 📚: https://cpython-devguide--1296.org.readthedocs.build/getting-started/setup-building/
=> Add iOS instructions to the devguide

documentation/markup.rst, documentation/style-guide.rst
Summarizing and codifying the advice discussed in https://github.com/python/docs-community/issues/52
----
📚 Documentation preview 📚: https://cpython-devguide--1294.org.readthedocs.build/
=> Avoid over-linking #1293

developer-workflow/stdlib.rst
Fixes https://github.com/python/devguide/issues/1285.
I wasn't sure where to put it, so went for `developer-workflow/stdlib.html`.
Is there a better place?
----
📚 Documentation preview 📚: https://cpython-devguide--1300.org.readthedocs.build/
=> Document style on naming env vars

include/release-cycle.json
3.11.9 was the last bugfix with binary installers.
* https://peps.python.org/pep-0664/
----
📚 Documentation preview 📚: https://cpython-devguide--1303.org.readthedocs.build/
=> Python 3.11 is now security-only

getting-started/pull-request-lifecycle.rst, getting-started/setup-building.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1306.org.readthedocs.build/
=> Add pre-commit setup to the Lifecycle of a pull request

conf.py, core-developers/committing.rst, developer-workflow/communication-channels.rst, documentation/markup.rst, documentation/translating.rst, getting-started/pull-request-lifecycle.rst, index.rst
Added as Sphinx `extlinks` in https://github.com/python/cpython/pull/117850.
We can also take advantage of the PyPI role here.
----
📚 Documentation preview 📚: https://cpython-devguide--1307.org.readthedocs.build/documentation/markup/#roles
=> Document custom CVE, CWE and PyPI roles

getting-started/setup-building.rst
- python/cpython#115119
----
📚 Documentation preview 📚: https://cpython-devguide--1313.org.readthedocs.build/
=> Update deps and build instructions wrt. libmpdecimal

include/release-cycle.json
Set 3.14 to "feature" and 3.13 to "prerelease".
----
📚 Documentation preview 📚: https://cpython-devguide--1319.org.readthedocs.build/
=> Python 3.14 is now `main`

getting-started/setup-building.rst
Similar to https://github.com/python/devguide/pull/1317.
For example, `yum` has short instructions:
As does `DNF`:
But `apt` is much longer, so it's good to tidy it away when not relevant:
----
📚 Documentation preview 📚: https://cpython-devguide--1318.org.readthedocs.build/getting-started/setup-building/#install-dependencies
=> Linux: Remove outdated `yum` instructions

.readthedocs.yml, Makefile
Using uv to install dependencies is quicker than pip.
On Read the Docs, it adds 1 second to install uv, and then cuts the docs build time from 28s -> 13s, overall halves the time from 28s -> 14s.
pip: https://beta.readthedocs.org/projects/hugovk-devguide/builds/24341331/
uv: https://beta.readthedocs.org/projects/hugovk-devguide/builds/24342365/
Locally, running `make clean; time make venv` with a warm cache:
pip: `make venv  4.05s user 0.92s system 91% cpu 5.451 total`
uv: `make venv  0.03s user 0.19s system 119% cpu 0.179 total`
`make html` is the same for both. 
Overall, `make clean html` goes from 7s -> 3s.
----
📚 Documentation preview 📚: https://cpython-devguide--1320.org.readthedocs.build/
=> makefile/RTD: Use uv if installed

developer-workflow/c-api.rst, getting-started/pull-request-lifecycle.rst, triage/labels.rst
"Feature release/version" is the terminology used at https://devguide.python.org/developer-workflow/development-cycle/#devcycle and for example [PEP 602](https://peps.python.org/pep-0602/) (Annual Release Cycle for Python).
* Fix 'major release' -> 'feature release'
These used major release when they really meant feature release.
* Prefer 'feature release' over 'minor release/version'
Minor release is fine, but feature release is clearer.
----
📚 Documentation preview 📚: https://cpython-devguide--1328.org.readthedocs.build/
=> Prefer "feature release"

core-developers/experts.rst
* Added myself (as the author of PEP 730) and @ned-deily (as the Tier 3 platform sponsor) as experts for iOS
* Added @mhsmith (as the author of PEP 738) and @encukou (as the Tier 3 platform sponsor) as experts for Android.
* Volunteered myself as an expert on macOS
----
📚 Documentation preview 📚: https://cpython-devguide--1330.org.readthedocs.build/
=> Add experts for mobile platforms.

internals/compiler.rst
Fixes issues found while reading the document.
- Corrects double negations
- Fixes references to non-existent ADDOP_LOAD_CONST_NEW
- Improves grammar
----
📚 Documentation preview 📚: https://cpython-devguide--1336.org.readthedocs.build/
=> Minor logic, grammar, and typo fixes

developer-workflow/development-cycle.rst
- @JacobCoffee has started as PSF Infrastructure Engineer
- Van is no longer acting as counsel to the PSF and owner role was removed some time ago
----
📚 Documentation preview 📚: https://cpython-devguide--1345.org.readthedocs.build/
=> update python organization owners

documentation/style-guide.rst
The Editorial Board would like to amend the style guide to include slashes and stars in function signatures in the style guide.
----
📚 Documentation preview 📚: https://cpython-devguide--1344.org.readthedocs.build/
=> Function signatures should use slash/star as needed

developer-workflow/index.rst, developer-workflow/psrt.rst
This documents the process for PSRT coordination which matches the proposal sent to the Python Security Response Team. Note that GitHub Security Advisories are not yet active for the CPython repository, but this process works mostly the same just without a canonical place to record the information and collaborate.
cc @zooba @gpshead @ned-deily @warsaw 
----
📚 Documentation preview 📚: https://cpython-devguide--1348.org.readthedocs.build/
=> Add PSRT coordination process and messaging templates

Makefile
Like https://github.com/python/cpython/pull/122662 and https://github.com/python/peps/pull/3891.
This is mostly to keep the `Makefile`s similar in each repo to ease maintenance.
Also remove the `make serve` stub, the target was removed in April 2022 in https://github.com/python/devguide/pull/826.
----
📚 Documentation preview 📚: https://cpython-devguide--1362.org.readthedocs.build/
=> Remove GNU make-specific directive from Makefile

developer-workflow/development-cycle.rst
This is a request to add myself as a repository admin to the python/cpython repository to be able to evaluate GitHub Security Advisories (GHSA) for a Python Security Response Team ticketing system.
GHSA is a strange feature, where only admins have the ability to "accept" reports and close tickets, even when other users and teams are added as "Collaborators" to a specific ticket (from what I can see, collaborators only have the ability to edit an advisory but not)
I wanted to add bedevere-like commands to the [PSRT GitHub bot](https://github.com/python/psrt-ghsa-bot) that collaborators could type in comments in order to change the state of GHSAs, but there is no API to retrieve the comments of an advisory. This means that for now if we're going to migrate to GHSA we need an admin clicking …
=> Request 'sethmlarson' be added as repo admin

make.bat
This is a follow-up of:
* #1362 
The PR removed the `make serve` target from the `Makefile` but not from `make.bat`.
---
Slightly unrelated, but I noticed that the `serve` replacement -- `htmllive` -- seems to be missing from `make.bat`.  `htmllive` (formerly known as `autobuild`) was introduced in:
* #1208 
`sphinx-autobuild` seems to be multiplat, so it should be possible to add it for Windows too.
----
📚 Documentation preview 📚: https://cpython-devguide--1365.org.readthedocs.build/
=> Remove obsolete `serve` target from `make.bat`.

getting-started/setup-building.rst
The dev guide pins the version of OpenSSL to version 3.0, but the current latest version i 3.3.1 (July 2024).
This change pins the OpenSSL version to 3.
----
📚 Documentation preview 📚: https://cpython-devguide--1349.org.readthedocs.build/
=> Use latest version of OpenSSL

internals/exploring.rst
https://github.com/paulross/PythonExtensionPatterns http://pythonextensionpatterns.readthedocs.org/en/latest/index.html
----
📚 Documentation preview 📚: https://cpython-devguide--1367.org.readthedocs.build/
=> Exploring: Python Extension Patterns v0.2.1 now supports Python 3.9 to Python 3.13.

documentation/style-guide.rst
This pull request fixes a typographical error in the `documentation/style-guide.rst` file. The word "knoweldge" has been corrected to "knowledge".
- **File Changed:** `documentation/style-guide.rst`
- **Correction:** The term "knoweldge" was incorrectly spelled and has been updated to "knowledge" to ensure clarity and accuracy in the documentation.
Thank you for reviewing this PR!
----
📚 Documentation preview 📚: https://cpython-devguide--1368.org.readthedocs.build/
=> Fix typo in documentation/style-guide.rst: Correct "knoweldge" to "knowledge"

.github/workflows/ci.yml
On a [recent PR](https://github.com/python/devguide/pull/1361), re-packing the cache took more time than the actual job. GHA runners have fast internet connections and we don't use many packages, it probably isn't worth using the cache. Also, we can switch to using `uv` for faster times.
Timings: 
| Timings | [Old](https://github.com/python/devguide/actions/runs/10386392593/job/28757574601?pr=1361) | [New](https://github.com/python/devguide/actions/runs/10386725054/job/28758622281?pr=1369) |
|--------|--------|--------|
| Run actions/checkout@v4          | ~0s    | ~0s    |
| Run actions/setup-python@v4      | ~0s    | ~0s    |
| Install uv                       | N/A    | 1s     |
| Build docs                       | 17s    | 12s    |
| Link check                       | 1m 30s | 1m 22s …
=> Use `uv` to install packages

Makefile, make.bat, make.ps1
Sphinx added this format [in 2014](https://github.com/sphinx-doc/sphinx/commit/91d92be8adae2e44e1e23e1c07b7088c35261abf). Nevertheless, it is the "modern" format, and far less verbose in the Makefile.
A
----
📚 Documentation preview 📚: https://cpython-devguide--1370.org.readthedocs.build/
=> Use "modern" Makefile template

.flake8, .pre-commit-config.yaml, .ruff.toml, _tools/generate_release_cycle.py
I've set `target-version = "py312"` as that is what we have in CPython, but we could lower this requirement if wanted.
A
----
📚 Documentation preview 📚: https://cpython-devguide--1372.org.readthedocs.build/
=> Adopt Ruff

getting-started/git-boot-camp.rst
- Add item to uncheck "Copy main branch only" button
- Add `git fetch upstream` command to creating branches section
----
📚 Documentation preview 📚: https://cpython-devguide--1376.org.readthedocs.build/
=> Improve forking instructions (#1375)

conf.py, development-tools/index.rst, development-tools/warnings.rst
New warning tracking tooling was introduced to CPython GitHub Actions jobs for Ubuntu with https://github.com/python/cpython/pull/121730.
It was then added for macOS build and test jobs with https://github.com/python/cpython/pull/122211
New compiler options that will emit warnings for potential security issues are going to be introduced to CPython. This addition to the developers guide is intended to be a reference for developers if the warning tracking tooling fails GitHub Actions CI.
I intend further expand on this documentation with examples based on the warning flags that we introduce to CPython, how developers can attempt to refactor to avoid these warnings, and finer details on how to modify warning ignore files.
----
📚 Documentation preview 📚: …
=> Add compiler warning tracking tooling failure remediation guidance

development-tools/clang.rst
Remove instructions to build from source.
Clang 18.x or 20.x is much easier to get “normally” than 3.4 was, and it has its own documentation.
Mention the configure options, but keep the previous instructions (seting CC/CXX) as “thorough setup”.
Use the modern option name `-fsanitize-ignorelist`.
cc @picnixz 
----
📚 Documentation preview 📚: https://cpython-devguide--1378.org.readthedocs.build/
=> Modernize "Dynamic analysis with Clang"

documentation/style-guide.rst
These are the remaining items from the (private) Editorial Board style guide suggestions:
https://docs.google.com/document/d/1rSkUIGFuI5zDMYturyJCo9agYPQ-d53Z3MntSV0rB3E/edit
----
📚 Documentation preview 📚: https://cpython-devguide--1377.org.readthedocs.build/
=> Add further recommendations to the style guide

documentation/translating.rst
Adding guidance about how to translate code blocks. Related to https://github.com/python/cpython/pull/123408 CPython PR (issue https://github.com/python/cpython/issues/123407).
----
📚 Documentation preview 📚: https://cpython-devguide--1382.org.readthedocs.build/
=> Add a fragment about translating code examples

core-developers/experts.rst, versions.rst
Also add turtledemo expert (Today new codeowner) https://github.com/python/cpython/commit/1ce9e5880347346105693aba211f4c378f5a9b6a
----
📚 Documentation preview 📚: https://cpython-devguide--1383.org.readthedocs.build/
=> Python 3.14 now is the main branch

getting-started/setup-building.rst
Add a note to the linux/debian instructions for building all optional packages.  libmpdec-dev is removed from recent Debian and can safely be dropped from list of packages to install.
See: https://github.com/python/cpython/issues/119114
See: https://github.com/python/cpython/pull/119196
See also #1338 
----
📚 Documentation preview 📚: https://cpython-devguide--1371.org.readthedocs.build/
=> Update setup-building.rst with a note about libmpdec-dev missing from some Debian versions

make.bat
This pull request fixes #1366 issue by adding the `htmllive` command to the `make.bat` script.
----
📚 Documentation preview 📚: https://cpython-devguide--1373.org.readthedocs.build/
=> Add htmllive to make.bat 

.github/workflows/ci.yml, core-developers/committing.rst, developer-workflow/communication-channels.rst, getting-started/git-boot-camp.rst, getting-started/pull-request-lifecycle.rst, triage/github-bpo-faq.rst, triage/issue-tracker.rst
Docs: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-guilabel
Also change a "https://planetpython.org/" link to "[Planet Python](https://planetpython.org/)".
----
📚 Documentation preview 📚: https://cpython-devguide--1387.org.readthedocs.build/
=> Use Sphinx `guilabel` role for buttons

developer-workflow/extension-modules.rst
I missed this one (I should have looked at the rendering before...)
----
📚 Documentation preview 📚: https://cpython-devguide--1391.org.readthedocs.build/developer-workflow/extension-modules/#updating-modules-setup-bootstrap-stdlib-in
=> Fixup in "Explain how to add an extension module" PR.

core-developers/become-core-developer.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1396.org.readthedocs.build/
=> Add a template for the core developer nomination poll

core-developers/experts.rst
I've resigned as a Python core developer (some weeks ago); this PR removes me from the experts list.
----
📚 Documentation preview 📚: https://cpython-devguide--1397.org.readthedocs.build/
=> Remove mdickinson from experts.rst

conf.py, getting-started/setup-building.rst
We've been getting some rate limiting checking stackoverflow.com, resulting in a 10-minute timeout. Let's ignore it.
Plus fix the XZ link, the old one was removed because it was created by the backdoor author.
```
...
(getting-started/setup-building: line  780) broken    https://xz.tukaani.org/xz-utils/ - HTTPSConnectionPool(host='xz.tukaani.org', port=443): Max retries exceeded with url: /xz-utils/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2b90d6b200>: Failed to resolve 'xz.tukaani.org' ([Errno -2] Name or service not known)"))
(developer-workflow/development-cycle: line  234) ok        https://github.com/python/devguide
(   triage/labels: line   33) ok        https://github.com/python/cpython/labels/type-security
(documentation/devguide: line …
```
=> Fix linkcheck

development-tools/warnings.rst
Add guidance for updating the compiler warning ignore files based on new capabilities added to the tooling in https://github.com/python/cpython/pull/124193
New features are ability to ignore entire files or warnings with a wildcard. Also minor updates to compiler output options: now `gcc` and `clang`.
=> Warning ignore file modification guidance for check warning tooling

getting-started/pull-request-lifecycle.rst
Sometimes contributors click the "Update branch" button to merge in `main` into their PR, which is fine if there's a good reason, but if not, pings anyone subscribed to the PR, and uses up CI limited resources, which can cause delays on other PRs.
Good reasons to click it include wanting to update an old PR, to make sure it still passes CI. Or if the PR is failing, and the some tests/config has been updated in `main`.
I occasionally need to tell contributors this in PRs. Let's add a section to the devguide so we have something handy to link to. Here's some proposed text, happy to change it.
Preview: https://cpython-devguide--1392.org.readthedocs.build/getting-started/pull-request-lifecycle/#update-branch-button
=> Add guidance about the 'Update branch' button

documentation/devguide.rst
- update the documentation to specify that cpython docs are updated daily
- removed the previous implication that updates occur only with cpython releases
- clarified the connection between daily updates and the cpython release workflow
This PR updates the documentation to clarify the update workflow for the CPython documentation. The previous text implied that updates only occurred with CPython releases, but the documentation is actually updated on a daily basis. This change ensures accurate and up-to-date information about the documentation workflow.
- Revised the description of the CPython documentation update process.
The original text did not fully reflect the frequency of CPython documentation updates. By specifying that updates occur daily, this pull request provides a more …
=> Clarify the documentation update process

Makefile, requirements.txt
Closes #1390.
A
----
📚 Documentation preview 📚: https://cpython-devguide--1400.org.readthedocs.build/
=> Require sphinx-autobuild>=2024.9.19

getting-started/setup-building.rst
Most of the relevant information is in the README in the CPython repository, so we can just reference that.
----
📚 Documentation preview 📚: https://cpython-devguide--1402.org.readthedocs.build/
=> Add Android instructions to the devguide

getting-started/fixing-issues.rst
The TODO has been there for 14 years.
Closes #1409 
----
📚 Documentation preview 📚: https://cpython-devguide--1412.org.readthedocs.build/
=> Remove the inactionable TODO

documentation/markup.rst
See https://github.com/python/cpython/issues/121277
----
📚 Documentation preview 📚: https://cpython-devguide--1413.org.readthedocs.build/
=> Document ``next`` in versionadded & similar directives

testing/new-buildbot-worker.rst
looks like this link became style, and the relevant information in the buildbot docs moved around.
----
📚 Documentation preview 📚: https://cpython-devguide--1422.org.readthedocs.build/
=> Update the link to the buildbot docs about setting up the worker as a Windows service

testing/new-buildbot-worker.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1421.org.readthedocs.build/
=> gh-1420: Add a note about long paths support to Windows buildbot setup

getting-started/setup-building.rst
I found that I needed all of these to get a CentOS-based buildbot worker to build most optional modules and pass all tests
----
📚 Documentation preview 📚: https://cpython-devguide--1423.org.readthedocs.build/
=> Add more packages to CentOS setup instructions

internals/interpreter.rst
See https://github.com/python/cpython/pull/124989
=> gh-124989: remove exception related details which have moved to cpython/InternalsDoc

include/release-cycle.json
Ahead of the 3.13.0 release later today
A
----
📚 Documentation preview 📚: https://cpython-devguide--1429.org.readthedocs.build/
=> Latest and greatest (3.13.0)

triage/labels.rst
- Documents new `infra` label from https://github.com/python/core-workflow/issues/450		
Closes: #1418
----
📚 Documentation preview 📚: https://cpython-devguide--1432.org.readthedocs.build/
=> feat: add `infra` label

getting-started/setup-building.rst
As detailed in https://github.com/python/cpython/issues/89452#issuecomment-1115525666, Homebrew makes a specific change to `gdbm` that confuses the build of 3.10 and below into picking incompatible headers/libs, so `dbm` segfaults at runtime.
It's fixed in 3.11; older source-only releases only get a workaround: pass `--with-dbmliborder=gdbm:ndbm` to `configure`.
---
(3.8 is now EOL, but I don't want to remove mentions of it in *this* PR, even if it's textually nearby.)
----
📚 Documentation preview 📚: https://cpython-devguide--1433.org.readthedocs.build/
=> Use --with-dbmliborder or macOS+Homebrew on 3.10 and below

.ruff.toml, _tools/generate_release_cycle.py
`/usr/bin/python3` is still 3.10 in some widely-used distros and the
support requirement is not onerous, needing only to use a longer-lived
alias for the same object (`assert datetime.UTC is datetime.timezone.utc`
holds where both exist).
See also #1097, #1107.
----
📚 Documentation preview 📚: https://cpython-devguide--1436.org.readthedocs.build/
=> Restore support for Python 3.10 to build

developer-workflow/development-cycle.rst, getting-started/setup-building.rst, internals/garbage-collector.rst
Also update examples to use more relevant versions, and remove some outdated info about 3.4 and earlier.
----
📚 Documentation preview 📚: https://cpython-devguide--1434.org.readthedocs.build/
=> Remove mentions of EOL Python 3.8

conf.py, core-developers/motivations.rst, developer-workflow/communication-channels.rst, developer-workflow/extension-modules.rst, developer-workflow/lang-changes.rst, getting-started/git-boot-camp.rst, getting-started/setup-building.rst, triage/issue-tracker.rst, triage/labels.rst
- **Update linkcheck configuration for unavoidable link issues**
- **Update the home of the python-checkins webhook**
- **Fix broken extlink usage**
- **Fix renamed PEP-0 section link**
- **Update redirected links**
- **Fix links to labels with spaces**
- **Remove dead link**
----
📚 Documentation preview 📚: https://cpython-devguide--1437.org.readthedocs.build/
=> Fix linkcheck issues

developer-workflow/extension-modules.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1438.org.readthedocs.build/
=> Fix reference warnings caused by removal of __file__ from cpython docs

contrib/code/index.rst, core-developers/become-core-developer.rst, core-developers/committing.rst, core-developers/motivations.rst, core-developers/responsibilities.rst, developer-workflow/development-cycle.rst, developer-workflow/psrt.rst, developer-workflow/stdlib.rst, getting-started/fixing-issues.rst, getting-started/git-boot-camp.rst, getting-started/pull-request-lifecycle.rst, getting-started/setup-building.rst, index.rst, testing/buildbots.rst, triage/triaging.rst
"Changeset" is gone completely.  "Patch" remains when discussing a change supplied as a textual diff, but is otherwise removed in favor of "pull request," "fix," or "contribution."
----
📚 Documentation preview 📚: https://cpython-devguide--1446.org.readthedocs.build/
=> More uniform terminology: patch and changeset #1443

core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1473.org.readthedocs.build/
=> experts: add myself to initialization, venvs, and import machinery

testing/new-buildbot-worker.rst
Provide examples for managing the buildbot-worker
service through systemd unit files for systemd based
distributions.
=> Add info for systemd based distros

conf.py, getting-started/pull-request-lifecycle.rst
Closes https://github.com/python/cpython/issues/126133.
Re: https://github.com/python/cpython/issues/126133#issuecomment-2451271955, this is so we can link to this section if we get PRs attempting to update copyright years each year.
Feedback welcome on wording and where to put this in the devguide.
----
📚 Documentation preview 📚: https://cpython-devguide--1470.org.readthedocs.build/
=> Add advice on copyright notices and PRs

testing/run-write-tests.rst
This pull request adds documentation for the -R flag in the python -m test command, enabling reference leak checking. This feature helps developers identify memory leaks when modifying C code.
----
📚 Documentation preview 📚: https://cpython-devguide--1468.org.readthedocs.build/
=> gh-1463: Added Refleak Checker Option under testing.

developer-workflow/stdlib.rst
The "Python Cookbook" hasn't had a new recipe since July 2017, which is also the last time any recipe was added:
* https://code.activestate.com/recipes/langs/python/new/
* https://code.activestate.com/recipes/new/
Turns out code.activestate.com was decommissioned in 2018 and "shouldn’t be accessible at all", but they've not made that clear on the site itself:
* https://community.activestate.com/t/status-of-code-activestate-com/6028/2
It's been replaced by the https://github.com/ActiveState/code repo but that's not been updated in four years.
In summary, let's not suggest people try and post a recipe to gauge usefulness of an idea.
----
📚 Documentation preview 📚: https://cpython-devguide--1481.org.readthedocs.build/
=> Remove link to decommissioned Python Cookbook

conf.py, developer-workflow/development-cycle.rst
Based on the wording at https://discuss.python.org/t/request-python-organisation-on-pypi/26545/5
----
📚 Documentation preview 📚: https://cpython-devguide--1484.org.readthedocs.build/
=> Document the PyPI org policy

developer-workflow/development-cycle.rst
As detailed in [PEP 101](https://peps.python.org/pep-0101/#moving-to-end-of-life):
> * Freeze the state of the release branch by creating a tag of its current HEAD and then deleting the branch from the CPython repo. The current HEAD should be at or beyond the final security release for the branch: [...]
> 
> * If all looks good, delete the branch. [...]
Let's update the policy to match.
----
📚 Documentation preview 📚: https://cpython-devguide--1483.org.readthedocs.build/
=> Update repo RM role policy regarding EOL branches

documentation/translating.rst
Refs https://github.com/python/docs-community/issues/143.
----
📚 Documentation preview 📚: https://cpython-devguide--1488.org.readthedocs.build/
=> Documentation/Translating: add a link to docs translations dashboard

documentation/markup.rst
Found a small typo while reading. The plural is used instead of the singular. The following rows are all singular: "attribute definitions" ,  "attribute references", "reference labels".
----
📚 Documentation preview 📚: https://cpython-devguide--1491.org.readthedocs.build/
=> Typo in markup.rst

triage/labels.rst
There are also the mobile OS labels for iOS and Android which I can add to the PR if needed.
----
📚 Documentation preview 📚: https://cpython-devguide--1493.org.readthedocs.build/
=> Document the OS-Linux label

core-developers/become-core-developer.rst
Mention getting a python.org email address #1449
Added a section to the "How to become a core developer" document to inform core team members about how they can get a python.org email address. The new section includes a link to the PSF Board Policies on Email Addresses.
Fixes #1449
----
📚 Documentation preview 📚: https://cpython-devguide--1495.org.readthedocs.build/
=> Add section on obtaining a python.org email address for core team members

core-developers/motivations.rst
Also remove mention of mentioning multiprocessing, because that's not true anymore.
----
📚 Documentation preview 📚: https://cpython-devguide--1501.org.readthedocs.build/
=> Update Antoine's affiliation

documentation/translating.rst
This PR includes 3 minor improvements I noticed while reading the docs.
1. Changed "picker" to "switcher" which is more commonly used and the term in the PEP.
2. Added "The" before "consensus" for grammatical correctness, "version" to align with the question/title.
3. Removed unnecessary "some".
----
📚 Documentation preview 📚: https://cpython-devguide--1490.org.readthedocs.build/
=> Minor improvements to translating.rst

.github/CONTRIBUTING.md, developer-workflow/communication-channels.rst, getting-started/getting-help.rst
Fixes #1244 
I tried to update the references of the core development discussion. Need reviews.
----
📚 Documentation preview 📚: https://cpython-devguide--1249.org.readthedocs.build/
=> Update mailing list information in devguide

documentation/translating.rst
This PR updates the Persian translation entry in `documentation/translating.rst` to reflect the change in maintainer from Komeil Parseh to Revisto and updates the repository link accordingly.
This change reflects the transfer of coordination for the Persian translation, as discussed on the Python Docs Discord server.
CC @JulienPalard for approval.
----
📚 Documentation preview 📚: https://cpython-devguide--1512.org.readthedocs.build/
=> Update Persian Translation Entry to Reflect New Maintainer

documentation/translating.rst
Just adding @rffontenelle as the main contact for the Brazilian translation community.
----
📚 Documentation preview 📚: https://cpython-devguide--1514.org.readthedocs.build/
=> Add Rafael Fontenelle as a contact for pt_BR translations

core-developers/memorialization.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1517.org.readthedocs.build/
=> Clarify that @python.org email addresses don't get reused; reflow text to fit

triage/issue-tracker.rst
Fixed the format so it renders correctly.
----
📚 Documentation preview 📚: https://cpython-devguide--1520.org.readthedocs.build/
=> Remove extra indentations in `triage/issue-tracker.rst`

documentation/translating.rst
* Adds a mention about the GiHub organisation (added after a discussion on docs community monthly meeting; not sure if that FAQ section is the perfect place for that, but I don't have a better idea).
* Updates link to the translations dashboard (the dashboard has been moved to the organisation).
* Mentions bootstraper project (sibling to the cookiecutter).
* Improves the list of resources needed for language switcher inclusion.
----
📚 Documentation preview 📚: https://cpython-devguide--1507.org.readthedocs.build/
=> Documentation/Translating: note new GitHub organisation

developer-workflow/c-api.rst
Draft for now: this refers to an addition to `python:api-intro` that I'm proposing in https://github.com/python/cpython/pull/130686
----
📚 Documentation preview 📚: https://cpython-devguide--1524.org.readthedocs.build/
=> C API: mention the workgroup, and the need to be stricter than our public promises

documentation/translating.rst
The “Brasilian Portuguese” is commonly used as a language name, also it looks like the Hindi and Bengali doesn't need to be country-specific: Hindi is India-only language, Bengali is [the same](https://www.reddit.com/r/kolkata/comments/1e5exb1/guys_whats_the_difference_between_indian_bengali/) in both India and Bangladesh.
----
📚 Documentation preview 📚: https://cpython-devguide--1492.org.readthedocs.build/
=> Shorten names of country-specific languages

core-developers/memorialization.rst
Previously we had scary red messages:
```
devguide/core-developers/memorialization.rst:5: WARNING: Duplicate explicit target name: "here". [docutils]
devguide/core-developers/memorialization.rst:5: WARNING: Duplicate explicit target name: "here". [docutils]
```
----
📚 Documentation preview 📚: https://cpython-devguide--1532.org.readthedocs.build/
=> use page titles as link text to avoid warnings

getting-started/setup-building.rst
Heavily copied from Brett's WASI guide.
----
📚 Documentation preview 📚: https://cpython-devguide--1533.org.readthedocs.build/getting-started/setup-building/#emscripten
=> Add section on building for Emscripten

core-developers/committing.rst, developer-workflow/communication-channels.rst, getting-started/pull-request-lifecycle.rst
And blurb has its own repo now.
----
📚 Documentation preview 📚: https://cpython-devguide--1538.org.readthedocs.build/
=> Update info about new CLA bot

developer-workflow/extension-modules.rst, getting-started/setup-building.rst, index.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1541.org.readthedocs.build/
=> Ensure ``make -j`` uses a reasonable argument

getting-started/setup-building.rst, index.rst
Follow on from https://github.com/python/devguide/pull/1541.
If a macOS user does not have coreutils installed (for example, via Homebrew) then `$(nproc)` can fail:
```console
❯ make -j $(nproc)
zsh: command not found: nproc
./python.exe -E ./Tools/build/generate-build-details.py `cat pybuilddir.txt`/build-details.json
Checked 113 modules (35 built-in, 78 shared, 0 n/a on macosx-15.4-arm64, 0 disabled, 0 missing, 0 failed on import)
```
We want these instructions to work without further assistance for a beginner.
And I do have coreutils installed on my other machine, but not on this one.
`j8` seems a reasonable number for macOS, all new Macs seem to be at least 10, and the M1 was at least 8.
----
📚 Documentation preview 📚: https://cpython-devguide--1545.org.readthedocs.build/
=> Use `make -j8` for macOS

developer-workflow/development-cycle.rst
This note added in https://github.com/python/devguide/commit/ca1c216999b7d49f7a6f8a84c1b49a5575adef5a :
```rst
.. note::
For the 3.5 release we're trying something new. We're creating the 3.5
maintenance branch at the time we enter beta (3.5.0 beta 1).  This will
allow feature development for 3.6 to occur alongside the beta and release
candidate stabilization periods for 3.5.
```
It was rewritten in https://github.com/python/devguide/commit/ab247321b031f80895c98b67ee88c10e49f5a5df and removed in https://github.com/python/devguide/pull/1434.
----
📚 Documentation preview 📚: https://cpython-devguide--1546.org.readthedocs.build/
=> Remove outdated reference to note about 3.5 branch

Makefile, make.bat, make.ps1
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going says:
> From Sphinx 8.1, `--keep-going` is always enabled.
> ...
> Changed in version 8.1: `sphinx-build` no longer exits on the first warning, meaning that in effect `--fail-on-warning` is always enabled. The option is retained for compatibility, but may be removed at some later date.
We're using Sphinx 8.2:
https://github.com/python/devguide/blob/f1b7e2505ab681933931c3b32e7db3036fa50039/requirements.txt#L10
----
📚 Documentation preview 📚: https://cpython-devguide--1544.org.readthedocs.build/
=> Sphinx 8.1+: remove redundant `--keep-going`

getting-started/setup-building.rst
This PR removes a recently introduced (#1558) spurious whitespace in a code block.
----
📚 Documentation preview 📚: https://cpython-devguide--1560.org.readthedocs.build/
=> Remove extra whitespace

core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1565.org.readthedocs.build/
=> Update my experts list

documentation/translating.rst
In reference to issue 29 on the Editorial Board repo:
https://github.com/python/editorial-board/issues/29
----
📚 Documentation preview 📚: https://cpython-devguide--1566.org.readthedocs.build/
=> Add Jeff Jacobson as coordinator of Indonesian translation

documentation/translating.rst
After discussion with @jwjacobson, there will be at least two coordinating people in charge of Indonesian translation.
----
📚 Documentation preview 📚: https://cpython-devguide--1567.org.readthedocs.build/
=> Add Irvan Putra as coordinator of Indonesian translation

conf.py
We're getting rate limited on another link in the CI linkcheck, which causes the CI to timeout and fail:
```
(internals/exploring: line    1) ok        https://www.youtube.com/playlist?list=PLzV58Zm8FuBL6OAv1Yu6AwXZrnsFbbR0S
(developer-workflow/communication-channels: line  245) ok        https://www.youtube.com/watch?v=-Nk-8fSJM6I
(contrib/core-team/motivations: line  178) ok        https://www.murrayandwalker.com/
-rate limited-   https://www.gnu.org/software/autoconf/ | sleeping...
-rate limited-   https://www.gnu.org/software/autoconf/ | sleeping...
-rate limited-   https://www.gnu.org/software/autoconf/ | sleeping...
-rate limited-   https://www.gnu.org/software/autoconf/ | sleeping...
-rate limited-   https://www.gnu.org/software/autoconf/ | sleeping...
-rate limited- …
```
=> Exclude https://www.gnu.org/software/autoconf/ in linkcheck

conf.py, documentation/index.rst, documentation/translations/coordinating.rst, documentation/translations/index.rst, documentation/translations/translating.rst
I propose that the existing page be split into two pages, a page for each key audience, **coordinators**, and **translators**. This, will help keep the pages organized allowing for better expansion. That is, to [facilitate content on best practices](https://discuss.python.org/t/best-practices-in-docs-translation/94427/4) (@nedbat @irvan-putra @jwjacobson) and [to provide transperency](https://hackmd.io/@willingcn/Synk3LXWgl#First-steps) (@willingc).
----
📚 Documentation preview 📚: https://cpython-devguide--1575.org.readthedocs.build/
=> Split `translating.rst` into pages for Translators and Coordinators

documentation/start-documenting.rst
This PR adds a small section to `documentation/start-documenting` that informs the reader of how to build only certain documentation pages. I tested my instructions on Linux and Windows. Please let me know if any changes are needed!
Thanks,
Micha
----
📚 Documentation preview 📚: https://cpython-devguide--1562.org.readthedocs.build/
=> gh-1309: Document how to selectively build RST pages

getting-started/setup-building.rst
Along the way make using the container outside of GitHub Codespaces its own section.
----
📚 Documentation preview 📚: https://cpython-devguide--1581.org.readthedocs.build/
=> Add instructions on how to use the dev container image from GHCR

core-developers/experts.rst
I forgot to do this originally, oops.
----
📚 Documentation preview 📚: https://cpython-devguide--1596.org.readthedocs.build/
=> Add myself to the experts index

development-tools/clinic.rst
The word emphasis character `_` is not supported as reST markup.
----
📚 Documentation preview 📚: https://cpython-devguide--1608.org.readthedocs.build/
=> Fix markups for emphasis

Makefile, documentation/start-documenting.rst
Fixes #1607
----
📚 Documentation preview 📚: https://cpython-devguide--1611.org.readthedocs.build/
=> Prevent `make venv` from reporting success when it actually failed

triage/labels.rst
[Issue:1610](https://github.com/python/devguide/issues/1610)
The previous link to the `test-with-buildbots` label in the triaging guide pointed to a non-existent label URL (missing the `:hammer:` prefix).
This PR updates the link to use the correct URL-encoded label:
https://github.com/python/cpython/labels/%3Ahammer%3A%20test-with-buildbots
----
📚 Documentation preview 📚: https://cpython-devguide--1612.org.readthedocs.build/
=> issue:1610 Fix broken link to 🔨 test-with-buildbots label in triaging.rst

triage/labels.rst
Fixes https://github.com/python/devguide/issues/1589.
Fixes https://github.com/python/core-workflow/issues/563.
----
📚 Documentation preview 📚: https://cpython-devguide--1588.org.readthedocs.build/
=> Document `type-refactor`

getting-started/setup-building.rst
* drop --with-system-libmpdec on macOS (default to yes since 3.13)
* recommend deb.sury.org for Debian 12 and Ubuntu 24.04
----
📚 Documentation preview 📚: https://cpython-devguide--1598.org.readthedocs.build/
=> Update libmpdec-related instructions

getting-started/setup-building.rst
Also make sure that relevant shell snippets are formatted so they can be copy-and-pasted.
----
📚 Documentation preview 📚: https://cpython-devguide--1632.org.readthedocs.build/
=> Use tabs for easier use in WASI and container sections of Setup

documentation/style-guide.rst
Fixes https://github.com/python/docs-community/issues/129, which has been open for 11 months with 10 votes in favour of the Google guidance (Ned's comment + 9 👍), and no down votes, and no other suggestions.
----
📚 Documentation preview 📚: https://cpython-devguide--1636.org.readthedocs.build/documentation/style-guide/#specific-words
=> Add boolean to the style guide

documentation/translations/translating.rst
The coordinator listed may make it seem like one is not necessary, and I don't watch the mailing list which means I won't be able to help anyone who messages it.
----
📚 Documentation preview 📚: https://cpython-devguide--1640.org.readthedocs.build/
=> Remove translation coördinator for Hungarian

getting-started/setup-building.rst
https://github.com/python/devguide/issues/1638 : Update the `EBNF` abbreviation to `PEG` abbreviation (Parser Expression Grammar).
----
📚 Documentation preview 📚: https://cpython-devguide--1639.org.readthedocs.build/
=> gh-1638: update EBNF abbreviation to PEG

documentation/help-documenting.rst
Closes https://github.com/python/devguide/issues/1647
Also removes unused link.
----
📚 Documentation preview 📚: https://cpython-devguide--1648.org.readthedocs.build/
=> Add translating to `help-documenting` page

documentation/translations/coordinating.rst, documentation/translations/translating.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1657.org.readthedocs.build/
=> Translation: Mailing list has been retired

getting-started/setup-building.rst
When building Python 3.13.7 from source, two socket tests fail if `inetutils-inetd` isn't installed. This PR fixes #1654 
----
📚 Documentation preview 📚: https://cpython-devguide--1655.org.readthedocs.build/
=> Added dependency for containerized Ubuntu installation

core-team/experts.rst
As noticed by @StanFromIreland, there is currently no expert listed for `zoneinfo`, so I have added myself.
----
📚 Documentation preview 📚: https://cpython-devguide--1658.org.readthedocs.build/
=> Add pganssle to zoneinfo experts list
