python/devguide

- faq.rst
This is an initial draft of moving the faq to git commands.
> Change some mercurial docs to git docs in the faq

- README.rst
> Add RTD badges to README

- conf.py
- tools/templates/layout.html
Mirrors this change from cpython docs:
https://hg.python.org/cpython/rev/274b25cd501f
https://bugs.python.org/issue19489
> Move the search box from sidebar to header and footer.

- index.rst
- setup.rst
Attempt to address issue #36 
I'm open for suggestions to further improve this. Thanks.
> Made "install dependencies" as Step number one.

- committing.rst
- communication.rst
- coredev.rst
- faq.rst
- gdb.rst
- help.rst
- index.rst
- langchanges.rst
- patch.rst
Addresses #27 
Still working on some content migration -- not ready for review
> Remove references to FAQ and migrate content

- developers.rst
- gitdevs.rst
Fixing some small nits across the
docs.
> Fix nits in docs

- committing.rst
Partially addresses #44. 
Replacement for #57, which was opened against wrong branch.
@brettcannon ptal
> Update cherry-picking for git flow

- triaging.rst
I have started the update to Git/Github. Could you check and comment if you find some mistakes.
Thank you,
> update triaging.rst for Git/GitHub

- .travis.yml
- buildslave.rst
- conf.py
- coverage.rst
- documenting.rst
- faq.rst
This is a fork of #25 due to inactivity from the PR creator (thanks @kragniz for the initial PR).
Closes #3
> Add Travis support

- committing.rst
@brettcannon as promised I've started updating the `committing.rst` file to reflect git workflow. There are a few questions that popped-up while going through the doc. It's still WIP.
> Updating committing.rst to reflect new git workflow

- developers.rst
> Update developers to the GitHub workflow

- devcycle.rst
> Update devcycle.rst for GitHub

- committing.rst
> Fix up reST formatting

- committing.rst
- coredev.rst
> Update coredev.rst for GitHub

- communication.rst
- documenting.rst
- grammar.rst
- index.rst
- setup.rst
A fork of #67 to allow the closure of #50 .
> Clean mentions of Mercurial

- docquality.rst
- documenting.rst
Follow up from https://github.com/python/devguide/issues/85
> Advise using the latest stable version of Sphinx

- index.rst
- runtests.rst
- setup.rst
Redirect to the checked-in readme.txt for full details.
Fixes #90.
> Simplify Windows building instructions

- index.rst
Clarify that trivial do not need issues.
Mention that PR should include bpo-NNNN in the description.
Closes https://github.com/python/devguide/issues/104
> Quick Start section: Clarify bpo Issue creation and PR procedure

- README.rst
- Remove GitHub work section
- Remove github RTD badge
🎉
> README.rst: Remove GitHub work section

- docquality.rst
- pullrequest.rst
> #117: update section about helping with the devguide.

- pullrequest.rst
Though already specified in [the Quick Start section](http://cpython-devguide.readthedocs.io/index.html) I believe it is a good idea to restate it here when a further description of pull requests is made.
> Fix a typo in pullrequest.rst and add reference to bpo-NNNN too

- coverage.rst
- docquality.rst
reword sentence to state how a pull request is required (and fix <patch> ref)
> include reference to create a pull request for the tests

- README.rst
- Change to https url
- Fix target url (prev url was 404)
> README.rst: fix badge url

- setup.rst
Addressed comments reported in GH-122
> Handling of generated files after migrated to Github

- experts.rst
> Remove Guido as an asyncio expert

- docquality.rst
- pullrequest.rst
- setup.rst
- triaging.rst
> Use https instead of http if supported

- index.rst
Closes https://github.com/python/devguide/issues/145
> Add the reference to opensource.guide

- committing.rst
> Be a bit more strong with getting the CLA signed

- pullrequest.rst
Closes https://github.com/python/devguide/issues/156
> fix broken issue tracker link

- exploring.rst
- index.rst
> Add exploring chapter for newcomers to become familiar with codebase

- committing.rst
Closes https://github.com/python/devguide/issues/163
> Add paragraph about reverting a commit.

- setup.rst
> Detail explain how to install build dependencies on apt based system

- index.rst
> Python 2.7 EOL date not decided yet

- experts.rst
> Remove Nadeem Vawda from the experts list

- pullrequest.rst
Closes https://github.com/python/devguide/issues/195
> GitHub PR is strongly preferred.

- experts.rst
I'm following steps by step the [New Translation Procedure](https://www.python.org/dev/peps/pep-0545/#new-translation-procedure) according to [Migrate Github Repositories](https://www.python.org/dev/peps/pep-0545/#migrate-github-repositories) from [PEP 545](https://www.python.org/dev/peps/pep-0545).
> PEP 545: Add mdk as French translation coordinator.

- coverage.rst
- index.rst
- setup.rst
Based on my experience setting up my machine for cpython development.
> Added using virtual env to coverage, and made some clarifications in index and setup.

- experts.rst
@brettcannon, @ncoghlan, and @Mariatta Please review. Moving forward I plan to focus on documentation and education elements of CPython. Thanks!
> Add myself to devguide, docs, and turtle experts

- experts.rst
see https://mail.python.org/pipermail/doc-sig/2017-June/003958.html
> Adding Kushal Das as a coordinator for Bengali India translation

- gitbootcamp.rst
> Document how to apply patch from mercurial to git

- buildbots.rst
- buildslave.rst
- clang.rst
- committing.rst
- communication.rst
- compiler.rst
- coredev.rst
- coverage.rst
- developers.rst
- documenting.rst
- help.rst
- index.rst
- langchanges.rst
- motivations.rst
- setup.rst
- stdlibchanges.rst
- tracker.rst
Just use `make linkcheck` on the devguide
> Fix urls with the right redirect in the documentation

- committing.rst
- developers.rst
- gitbootcamp.rst
- pullrequest.rst
This should not be merged until larryhastings/blurb relocates to python/core-workflow, python/cpython is updated appropriately, and python/core-workflow#66 is closed.
> Document the news file format

- pullrequest.rst
Don't merge until:
Partial work for https://github.com/python/bedevere/issues/25
> Use skip "issue label" instead of "trivial"

- gitbootcamp.rst
> issue242: Creating a Pull request needs an additional step

- gitbootcamp.rst
After rebase, force push to origin
> Update 'sync with upstream' section

- gitbootcamp.rst
- pullrequest.rst
The devguide didn't seem to document how to delete remote branches.
I documented it and added a few links around.
> Document how to delete remote branches.

- compiler.rst
- exploring.rst
> #184: link to Green Tree Snakes.

- committing.rst
This Pull Request implements the changes proposed on #191. A very simple statement was added to the dev guide on my understanding of the proposed changes. If I need to add a more detailed explanation on when this is allowed or how to delete the branches (or anything else) I will be more than happy to change it. 😄
> Add exception regarding personal branches

- exploring.rst
Hello,
I made this pull request for the issue #230.
> Added a reference link to the python extension patterns guide.

- buildbots.rst
> Update URL to buildbot console.

- committing.rst
Add another checklist item, that the PR is first made against the `master` branch first.
> Update committing checklist.

- index.rst
Resolves #306 
cc @brettcannon
> Removes Firefox search-engine link that throws 404

- communication.rst
Will update with edited version of the video.
For now this should work I think :)
(I copied the text from the [talk abstract](https://www.pycascades.com/talks/setting-expectations-for-open-source-participation/))
> Link to Brett's talk from the communication page

- developers.rst
> Update Flovis by Floris in developers.rst

- conf.py
- tools/static/custom.css
Closes #351 
Preview build here: http://temp.theadora.io/devguide/index.html
> Add background color back to navigation bar

- .travis.yml
Fixes #292.
For example:
* https://docs.travis-ci.com/user/build-stages/
* https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail
> Run linkcheck on CI (but allow to fail)

- setup.rst
> Remove reference to OpenHatch

- documenting.rst
> Remove Sphinx dependencies and mention blurb and python-docs-theme

- experts.rst
See: https://mail.python.org/pipermail/doc-sig/2018-May/004030.html
> Adding adrianliaw as the coordinator of the zh-tw translation.

- committing.rst
> Clarify GH web UI usage by core devs

- gitbootcamp.rst
I think this is very nice article for everyone
want to know how to write good commit message.
> Add link to "How to Write a Git Commit Message"

- documenting.rst
> Add a few missing in-use directives

- documenting.rst
I'm opening this by suggestion of @zware in: https://github.com/python/cpython/pull/9791
> Use "should" instead of "must" when talking about versionchanged second argument

- developers.rst
> Add entry for Jason R. Coombs based on his best recollection.

- developers.rst
@vstinner Could you check if this PR is correct for @csabella 
Thank you so much.
> Add Cheryl Sabella as Core-dev

- triaging.rst
> Typo: asycio -> asyncio

- experts.rst
> Add @pradyunsg to the experts index

- triaging.rst
I've created the `newcomer friendly` keyword in bpo.
https://bugs.python.org/keyword22
> Document the new "newcomer friendly" keyword in bpo

- setup.rst
Current "autoconf" tool is version 2.69.
> Update autoconf version

- developers.csv
- developers.rst
> Add GitHub sernames for core dev team list

- garbage_collector.rst
I made some minor changes. I hope they make the doc better.
> minor wording fixes

- documenting.rst
superseding https://github.com/python/devguide/pull/558
> Doc translations: update Polish

- garbage_collector.rst
Adding the missing `del link_4` is the important change.
> Fixed example and explained its result, fixed typos

- index.rst
Add blurb tool process in quick reference guide.
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> Add information about blurb tool

- developers.csv
- developers.rst
It now includes when someone left the team and any notes about their membership.
> Update the format of the developer log

- pullrequest.rst
Continuation of #599 and matches the hint in `patchcheck.py`
> Add more information about blurb

- experts.rst
> Add PEG Parser experts

- experts.rst
> Fix typo in my username in the experts file

- documenting.rst
Changing the arabic coordinator. Don't merge before getting a written confirmation here from Mr Ibrahim.
> Changing Arabic coordinator

- gitbootcamp.rst
A draft set of changes from the points suggested in https://github.com/python/devguide/issues/645
> Syncing with Upstream more accessible (issue #645)

- devcycle.rst
I'm still an Administrator (for now?) but I'm no longer a Release Manager, as of sometime today I guess.
> Update my status in the Administrators list

- documenting.rst
> Made wording more welcoming

- devcycle.rst
> Updated Devcycle doc with Ee's name.

- devcycle.rst
This is how I imagine things work in the beta & RC, but I'm likely wrong:
- beta: docs & test changes are welcome
- RC: no trivial changes
@pablogsal, as the RM, could you please review and make any changes necessary?
> devcycle: Clarify doc & test changes in Beta & RC

- triaging.rst
just a minor grammar improvement
> minor grammar improvement

- buildbots.rst
- communication.rst
- documenting.rst
- help.rst
Rationale:
https://mail.python.org/archives/list/python-dev@python.org/thread/FQW44V4DZFX4GAGOAMAZAN5KDQXCASDU/
> Migrate from Freenode to LiberaChat

- compiler.rst
> Sync section 25.7 with Python/compile.c

- requirements.txt
> Restrict the version of sphinx-copybutton to pick up bugfixes

- compiler.rst
This follows dicucssion here: https://bugs.python.org/issue42349
> bpo-42349: Clarify basicblocks and give some examples

- compiler.rst
- grammar.rst
- index.rst
- parser.rst
- requirements.txt
> Add a new guide on how to understand and use the PEG parser

- setup.rst
> Link to configure docs in compilation guide

- documenting.rst
I am unfortunately back to being the Arabic coordinator
> Update Arabic coordinator

- parser.rst
> Fix grammar in the title of the Parser guide

- garbage_collector.rst
> Fix typo in garbage_collector

- langchanges.rst
not sure if this is considered a minor fix, let me know if I should file an issue for this first
> Update reference to the parser from LL(1) to PEG

- parser.rst
some duplications, typo, minor grammar (haha)
> Several fixes in parser page

- parser.rst
> Update AST actions helper location in the PEG parser

- devcycle.rst
Ewa is no longer Executive Director of PSF
> Update GitHub Owners doc.

- gitbootcamp.rst
> Promote GitHub CLI in Git Bootcamp section

- gitbootcamp.rst
> Fix GitHub links in Git Bootcamp section

- triaging.rst
It's a bit of a late addition, but better late than never? :)
> Add description of GitHub PR field

- gitbootcamp.rst
> Add section about comparing changes to the git bootcamp

- .github/workflows/ci.yml
> Run the tests using Python 3.10

- documenting.rst
Replaces and closes https://github.com/python/devguide/pull/638.
Most of the changes in https://github.com/python/devguide/pull/638 were invalid, except the addition made in this PR.
I've put @aliya-rahmani as commit co-author.
> Add link to Polish translation request email

- documenting.rst
- updated mailing list link
- mentioned the translation work group
> docs: Translations section links fix

- experts.rst
And people can assign issues to me.
I guess there's also some config I need to change so I show up in the autocomplete list on BPO, so I'll go look for that next.
> Become an expert for typing

- exploring.rst
Fixes double link in the doc. 
_Update- I signed the CLA after @the-knights-who-say-ni raised the error below._
> Fixes double link

- documenting.rst
Add the Persian language. Of course, I'm not sure if other people are working on the Persian language
> Add persian to documenting.rst

- appendix.rst
- c-api.rst
- committing.rst
- compiler.rst
- coverage.rst
- documenting.rst
- garbage_collector.rst
- parser.rst
- pullrequest.rst
- runtests.rst
- tracker.rst
`sed -z -i 's/ \n/\n/g' *.rst`
> Remove whitespace from .rst files, as per make check

- experts.rst
> Deduplicate translators tables.

- experts.rst
> Update my expert index entries.

- .github/workflows/ci.yml
Rename the CI check to be more explicit.
> Rename CI check.

- .github/ISSUE_TEMPLATE/bug_report.md
"enhancementfor" -> "enhancement for"
> Issue template: fix typo

- experts.rst
I don't think I've ever edited this... some obvious ones were missing (subprocess, hello!) and others make sense for me as well.
> Splat my name on more expertise areas.

- setup.rst
> WIP: Mention and link to the macOS readme in the repo.

- devcycle.rst
documents @python/organization-owners
> Document new way of highlighting GitHub Organization Owners

- setup.rst
> Fix code block in the ABI regenerate section

- gitbootcamp.rst
- pullrequest.rst
- setup.rst
instead of using git checkout
https://github.com/python/devguide/issues/890
> gh-890: Use git switch to switch to branch

- gh-labels.rst
- setup.rst
maintenace -> maintenance
Maintainance -> Maintenance
> Fix some minor typos

- versions.rst
> PEP 693 is the Python 3.12 release schedule

- developer-workflow/porting.rst
Fix minor typos in "Porting to a New Platform"
> Fix typos in porting.rst

- internals/parser.rst
Those "errors" will be spotted by the next release of sphinx-lint (that's how I found them).
> Found two default-roles.

- versions.rst
> Update 3.11 with actual release date of 3.11.0

- core-developers/experts.rst
Removing Tarek as per @brettcannon message in discord.
> Update sysconfig experts

- documentation/translating.rst
> Add Maciej Olko as Polish translation coordinator

- .github/workflows/ci.yml
- .readthedocs.yml
Build the docs on GitHub Actions and Read the Docs using the new Python 3.11.
> Build with Python 3.11 on CI and RTD

- core-developers/experts.rst
> Add hugovk to the experts index

- conf.py
Furo supports adding an edit button to the top-right of pages, so you can easily get from the docs page to the relevant page on GitHub.
Without this, you need to open the repo page yourself, then navigate to find the page and edit.
https://pradyunsg.me/furo/customisation/edit-button/
https://cpython-devguide--1010.org.readthedocs.build/internals/parser/ -> 🖊️ -> https://github.com/python/devguide/edit/main/internals/parser.rst
> Add edit button to theme

- documentation/translating.rst
Add docs.python.org link to the Turkish section in the table.
> Add Doc link to Turkish section

- core-developers/experts.rst
As @AlexWaygood [suggested](https://github.com/python/cpython/pull/100782#issuecomment-1373563789)!
> Add barneygale to experts index

- internals/garbage-collector.rst
> Correct the description of generation thresholds in the gc docs

- internals/parser.rst
> Fix one character typo

- core-developers/experts.rst
- core-developers/motivations.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1086.org.readthedocs.build/
> Add willingc as asyncio expert and update motivation entry

- documentation/markup.rst
Fixes #1091.
----
:books: Documentation preview :books:: https://cpython-devguide--1092.org.readthedocs.build/
> Document custom CPython roles.

- include/release-cycle.json
----
:books: Documentation preview :books:: https://cpython-devguide--1130.org.readthedocs.build/versions/
> Python 3.7 is EOL

- index.rst
Add a link to blurb repository to see more information about it.
Closes: #1136 
----
:books: Documentation preview :books:: https://cpython-devguide--1137.org.readthedocs.build/
> Update link to blurb documentation

- index.rst
Add "Helping with the Developer’s Guide" to the Documentarians column in the table. It's one of the menu entries.
----
:books: Documentation preview :books:: https://cpython-devguide--1164.org.readthedocs.build/
> Add "Helping with the Developer’s Guide" to documentarians column

- include/release-cycle.json
Re: https://github.com/python/devguide/pull/1174#pullrequestreview-1653063036
----
:books: Documentation preview :books:: https://cpython-devguide--1175.org.readthedocs.build/
> Python 3.12 is now in bugfix

- getting-started/git-boot-camp.rst
```console
❯ gh alias list
co: pr checkout
```
For less typing.
---
Also don't say "simply":
* https://www.knowledgeowl.com/blog/posts/dont-say-simply-jim-fisher/
* https://www.youtube.com/watch?v=gsT2BBWBVmM&ab_channel=WritetheDocs
----
:books: Documentation preview :books:: https://cpython-devguide--1182.org.readthedocs.build/
> Replace 'gh pr checkout' with 'gh co' alias

- core-developers/developers.csv
- core-developers/motivations.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1185.org.readthedocs.build/
> Update details for Alyssa Coghlan

- core-developers/developers.csv
----
:books: Documentation preview :books:: https://cpython-devguide--1197.org.readthedocs.build/
> Add Adam Turner to the developer log

- getting-started/getting-help.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1203.org.readthedocs.build/
> Add missing word

- core-developers/experts.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1204.org.readthedocs.build/
> update my `experts` entries

- core-developers/experts.rst
----
:books: Documentation preview :books:: https://cpython-devguide--1209.org.readthedocs.build/
> Update my experts index

- .editorconfig
- .pre-commit-config.yaml
- getting-started/git-boot-camp.rst
Fixes https://github.com/python/devguide/issues/105.
Based on the instructions in the first post there. I've been using this for a couple of months.
Also add the [.editorconfig from CPython](https://github.com/python/cpython/blob/main/.editorconfig) and add some handy pre-commit hooks.
----
📚 Documentation preview 📚: https://cpython-devguide--1255.org.readthedocs.build/getting-started/git-boot-camp/#git-worktree
> Document Git worktree

- documentation/translating.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1254.org.readthedocs.build/
> Hello python-docs-ru

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1266.org.readthedocs.build/
> Add myself as a JIT expert

- core-developers/experts.rst
with github id of whose who stepped up in that thread https://discuss.python.org/t/im-stepping-down-as-sponsor-of-emscripten/41064/20
----
📚 Documentation preview 📚: https://cpython-devguide--1267.org.readthedocs.build/
> list community platform (emscripten) supporters github id

- core-developers/become-core-developer.rst
- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1271.org.readthedocs.build/
> Add Sam Gross & Nikita Sobolev, clarify how to announce

- documentation/help-documenting.rst
Fixes https://github.com/python/devguide/issues/886.
Add the last paragraph here:
----
:books: Documentation preview :books:: https://cpython-devguide--1229.org.readthedocs.build/documentation/help-documenting/#proofreading
> Document the python/proofreaders team

- core-developers/experts.rst
I cannot say that I know all about `typing` in Python, but I can still be helpful.
I don't want to be a codeowner on GitHub, because I will get too many notifications, but I can add myself here for better visibility for others: I am open to help, answer questions, and review PRs.
If @JelleZijlstra and @AlexWaygood agree :)
----
📚 Documentation preview 📚: https://cpython-devguide--1288.org.readthedocs.build/
> Add myself to `typing` experts

- documentation/translating.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1297.org.readthedocs.build/
> Add GR translation link and contacts

- index.rst
Helps https://github.com/python/core-workflow/issues/329.
The blurb code has been moved to https://github.com/python/blurb, let's update the link.
----
📚 Documentation preview 📚: https://cpython-devguide--1302.org.readthedocs.build/
> Update link to blurb's new home at python/blurb

- getting-started/setup-building.rst
For example:
----
📚 Documentation preview 📚: https://cpython-devguide--1317.org.readthedocs.build/getting-started/setup-building/#install-dependencies
> macOS: Add tabs for Homebrew/MacPorts and for 3.13+/3.11-3.12/3.8-3.10

- getting-started/getting-help.rst
- index.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1324.org.readthedocs.build/
> Remove office hours section

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1329.org.readthedocs.build/
> Add Russell Keith-Magee

- core-developers/experts.rst
I'm not an expert; the first time I've installed the Android SDK was to review Android/README.md when support was being finalzed. (FWIW, I like to think that a beginner's point of view helped there.)
As a PEP sponsor, I helped with the *process* side of getting the changes in.
I'm happy to help with Android support, as with any other part of Python; it's not special to me, nor I to it.
----
📚 Documentation preview 📚: https://cpython-devguide--1331.org.readthedocs.build/
> Remove myself as an Android expert

- documentation/translating.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1333.org.readthedocs.build/
> documentation/translating: Added github to Italian entry

- core-developers/experts.rst
- Sign up as a maintainer for the AST and symbol table
- Add @gaogaotiantian as a maintainer for pdb
- Remove some (though not all) modules that no longer exist
----
📚 Documentation preview 📚: https://cpython-devguide--1332.org.readthedocs.build/
> Updates to experts

- core-developers/developers.csv
Welcome!
----
📚 Documentation preview 📚: https://cpython-devguide--1335.org.readthedocs.build/
> Add Michael Droetboom and Tian Gao as core developers

- internals/garbage-collector.rst
Fixes a minor typographic error in the garbage collector documentation.
----
📚 Documentation preview 📚: https://cpython-devguide--1346.org.readthedocs.build/
> Fix a typo in garbage collector documentation

- testing/coverage.rst
Closes #1355 
----
📚 Documentation preview 📚: https://cpython-devguide--1356.org.readthedocs.build/
> Fix broken link

- core-developers/developers.csv
Re: https://discuss.python.org/t/vote-to-promote-ned-batchelder/57668/4
@nedbat Feel free to open a PR to add yourself to https://devguide.python.org/core-developers/experts/ if you like.
----
📚 Documentation preview 📚: https://cpython-devguide--1357.org.readthedocs.build/
> Add Ned Batchelder to core team

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- core-developers/become-core-developer.rst
- core-developers/responsibilities.rst
- developer-workflow/communication-channels.rst
- getting-started/setup-building.rst
- index.rst
- internals/interpreter.rst
- internals/parser.rst
- testing/new-buildbot-worker.rst
- triage/triage-team.rst
Fix most of the warnings from linkcheck: https://github.com/python/devguide/actions/runs/10538175700/job/29200391258?pr=1364#step:6:55
----
📚 Documentation preview 📚: https://cpython-devguide--1380.org.readthedocs.build/
> Update hyperlink redirects

- documentation/translating.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1386.org.readthedocs.build/
> Update GR translation contact

- core-developers/experts.rst
David Edelsohn still wants to be notified of AIX issues, see: https://github.com/python/cpython/issues/82809#issuecomment-2361112194
Update to his GitHub username.
----
📚 Documentation preview 📚: https://cpython-devguide--1401.org.readthedocs.build/
> Experts list: update David Edelsohn's user name

- core-developers/developers.csv
- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1405.org.readthedocs.build/
> Add Kirill Podoprigora to core developers

- core-developers/experts.rst
Update AIX Maintainers list, see #1406 
----
📚 Documentation preview 📚: https://cpython-devguide--1417.org.readthedocs.build/
> Update AIX Maintainers list

- include/release-cycle.json
----
📚 Documentation preview 📚: https://cpython-devguide--1427.org.readthedocs.build/
> Update 3.13.0 expected release date

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1439.org.readthedocs.build/
> Add Matt Page to core developers

- contrib/code/index.rst
- contrib/code/pull-request-lifecycle.rst
- contrib/contrib-plan.rst
- contrib/doc/devguide.rst
- contrib/doc/help-documenting.rst
- contrib/doc/index.rst
- contrib/doc/markup.rst
- contrib/doc/pull-request-lifecycle.rst
- contrib/doc/start-documenting.rst
- contrib/doc/style-guide.rst
- contrib/doc/translating.rst
- internals/index.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1454.org.readthedocs.build/
> Populate the docs section of the new contrib structure

- developer-workflow/grammar.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1457.org.readthedocs.build/
> add a title to fix a warning

- core-developers/motivations.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1460.org.readthedocs.build/
> Affiliation update for Alyssa Coghlan

- developer-workflow/development-cycle.rst
Before:
After:
----
📚 Documentation preview 📚: https://cpython-devguide--1464.org.readthedocs.build/
> Fix current admins table

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1471.org.readthedocs.build/
> Add Savannah Ostrowski

- core-developers/motivations.rst
Title says it all
----
📚 Documentation preview 📚: https://cpython-devguide--1480.org.readthedocs.build/
> Long overdue update to Barry's affiliations

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1485.org.readthedocs.build/
> Add Bénédikt Tran

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1487.org.readthedocs.build/
> Add Bénédikt Tran to `core-developers/experts.rst`

- documentation/translating.rst
With mention about Python Docs Discord channel.
----
📚 Documentation preview 📚: https://cpython-devguide--1489.org.readthedocs.build/
> Documentation/Translating: update how to get help

- versions.rst
Add a link to endoflife.date/python which has another useful visualization of Python lifecycles.
----
📚 Documentation preview 📚: https://cpython-devguide--1494.org.readthedocs.build/
> Update versions.rst to include link to endoflife.date/python

- Makefile
Similar to https://github.com/python/cpython/pull/129094.
----
📚 Documentation preview 📚: https://cpython-devguide--1498.org.readthedocs.build/
> Fix venv creation for the local Python using uv

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1508.org.readthedocs.build/
> Add kulikjak to Solaris Maintainers list

- core-developers/developers.csv
Reactivating status per @hugovk.
----
📚 Documentation preview 📚: https://cpython-devguide--1509.org.readthedocs.build/
> Reactivate my (Trent Nelson) status

- core-developers/developers.csv
- core-developers/experts.rst
See In Memoriam:
https://discuss.python.org/t/in-memoriam-michael-foord-1974-2025/78317
----
📚 Documentation preview 📚: https://cpython-devguide--1515.org.readthedocs.build/
> Memorialize Michael Foord

- core-developers/become-core-developer.rst
No issue opened, but this just clarifies a few points about the SC's and DiR's role in the new core dev approval process.
----
📚 Documentation preview 📚: https://cpython-devguide--1539.org.readthedocs.build/
> A few minor clarifications about the new developer process

- core-developers/experts.rst
At this point it has been years since I used Windows regularly; my knowledge has atrophied and I am no longer useful in this list.
----
📚 Documentation preview 📚: https://cpython-devguide--1540.org.readthedocs.build/
> Remove myself from the Windows expert list

- triage/labels.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1550.org.readthedocs.build/
> Correct grammar in label description

- include/release-cycle.json
2031, yikes!
----
📚 Documentation preview 📚: https://cpython-devguide--1552.org.readthedocs.build/
> Add Python 3.15

- core-developers/developers.csv
I got married! My GitHub handle will remain the same, though, because updating it is too much of a pain.
----
📚 Documentation preview 📚: https://cpython-devguide--1551.org.readthedocs.build/
> Change Savannah Ostrowski to Savannah Bailey

- conf.py
Request: @hugovk
----
📚 Documentation preview 📚: https://cpython-devguide--1556.org.readthedocs.build/
> Exclude github.com in linkcheck

- contrib/contrib-plan.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1563.org.readthedocs.build/
> use a forever link to docs discord invite

- _static/devguide_overrides.css
----
📚 Documentation preview 📚: https://cpython-devguide--1564.org.readthedocs.build/
> the prerelease label needs to be black

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1577.org.readthedocs.build/
> Add Peter Bierma to core developers

- core-developers/developers.csv
----
📚 Documentation preview 📚: https://cpython-devguide--1578.org.readthedocs.build/
> Add Tomas Roun to core devs

- core-developers/experts.rst
I don't consider myself an expert but I've worked in this area both in CPython and my $job so I thought it'd be useful to add myself here :)
----
📚 Documentation preview 📚: https://cpython-devguide--1584.org.readthedocs.build/
> Add tomasr8 to gettext & i18n

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1599.org.readthedocs.build/
> Reorder the list of argparse experts in alphabetical order.

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1597.org.readthedocs.build/
> Add "nascheme" in a few places.

- core-developers/experts.rst
----
📚 Documentation preview 📚: https://cpython-devguide--1601.org.readthedocs.build/
> experts: add myself as expert for annotationlib

- documentation/translations/translating.rst
Support @jwjacobson and @irvan-putra coordinating translation as discussed in https://discord.com/channels/935215565872693329/1372598660239593572
----
📚 Documentation preview 📚: https://cpython-devguide--1591.org.readthedocs.build/
> Add Lutfi Zuchri as a co-ordinator of the Indonesian translation
